"""Pydantic data contracts shared across the backend.

Money is always an integer number of rupees. Every field carries a description,
which also appears in the OpenAPI docs at ``/docs``.
"""

from ruko.models.common import (
    Certainty,
    EvidenceSpan,
    FundingSource,
    HoldingIntent,
    InterventionLevel,
    PaymentDestination,
    ProductClass,
    ReasonCode,
    RefusalClass,
    Severity,
    SignalSource,
    SourceRef,
    SourceType,
)
from ruko.models.decision import (
    AdverseMove,
    AttentionState,
    BaseRateFact,
    ExposureNumbers,
    InterventionDecision,
    MoneyRange,
    NumberRange,
    Reason,
)
from ruko.models.event import DecisionEvent, Signal
from ruko.models.inputs import InputType, NormalizedInput, RawInput, Script
from ruko.models.journal import JournalAction, JournalEntry, JournalOutcome
from ruko.models.profile import (
    AttentionCounts,
    Experience,
    PlannedDecision,
    ProtectedGoal,
    RecentContext,
    UserProfile,
    UserRules,
)
from ruko.models.recovery import RecoveryGuide, RecoveryScenario, RecoveryStep
from ruko.models.responses import (
    ClarifyOption,
    ClarifyQuestion,
    ClarifyResponse,
    ExplanationCard,
    PauseResponse,
    RecoveryEntry,
    RefusalResponse,
    ResponseMeta,
    SignalView,
    TemplateRef,
    TraceStep,
)

__all__ = [
    "AdverseMove",
    "AttentionCounts",
    "AttentionState",
    "BaseRateFact",
    "Certainty",
    "ClarifyOption",
    "ClarifyQuestion",
    "ClarifyResponse",
    "ExposureNumbers",
    "DecisionEvent",
    "EvidenceSpan",
    "Experience",
    "ExplanationCard",
    "FundingSource",
    "HoldingIntent",
    "InputType",
    "InterventionDecision",
    "InterventionLevel",
    "JournalAction",
    "JournalEntry",
    "JournalOutcome",
    "MoneyRange",
    "NormalizedInput",
    "NumberRange",
    "PauseResponse",
    "PaymentDestination",
    "PlannedDecision",
    "ProductClass",
    "ProtectedGoal",
    "RawInput",
    "Reason",
    "ReasonCode",
    "RecentContext",
    "RecoveryEntry",
    "RecoveryGuide",
    "RecoveryScenario",
    "RecoveryStep",
    "RefusalClass",
    "RefusalResponse",
    "ResponseMeta",
    "Script",
    "Severity",
    "Signal",
    "SignalSource",
    "SignalView",
    "SourceRef",
    "SourceType",
    "TemplateRef",
    "TraceStep",
    "UserProfile",
    "UserRules",
]
