// English chrome text (buttons, labels, empty and error states). Everything Ruko *says about
// a decision* comes from the backend's rendered templates instead. Hindi and Kannada live in
// hi.ts and kn.ts and must define every key here (the compiler checks), as drafts for native review.

import type { AppErrorKind } from "../services/api";
import type { RecordingProblem } from "../services/recorder";
import type { InterventionLevel, JournalAction } from "../types/api";

export const en = {
  privateByDesign: "Private by design",
  homeEyebrow: "Your decision space",
  homeTitle: "Before you act, take a moment.",
  homeBody:
    "A calm place to think through a financial decision. Ruko helps you pause; the choice stays yours.",
  shareSomething: "Share something",
  shareHint: "Bring in only what you choose to share.",
  thinkDecision: "Think through a decision",
  myRules: "My rules",
  myRulesHint: "Your commitments, on your terms",
  journal: "Journal",
  journalHint: "Look back at a decision",
  homeFooter: "Only what you share is analyzed · No broker, OTP or SMS access",
  workOutNumber: "Work out a number",
  workOutNumberHint: "A SIP, a goal, a fall in value",
  alreadyPaid: "I already paid",
  alreadyPaidHint: "Step-by-step help, in order",
  myPatterns: "My patterns",
  myPatternsHint: "What your own journal shows",
  settings: "Settings",
  settingsHint: "Language, text size, how much Ruko speaks",

  composeEyebrow: "Shared with Ruko",
  composeDecisionEyebrow: "Think through a decision",
  composeCalcEyebrow: "Work out a number",
  composeLabel: "Paste the message you received",
  composeDecisionLabel: "What are you thinking of doing?",
  composeCalcLabel: "What would you like to work out?",
  composeCalcExample: "For example: a SIP of 5000 a month for 10 years",
  composePlaceholder: "Paste or type the message here",
  composeAddScreenshot: "Add a screenshot instead",
  composeRemoveScreenshot: "Remove screenshot",
  composeScreenshotChosen: "Screenshot added",
  composeSubmit: "Look at this",
  composeEmpty: "Paste a message or add a screenshot first.",
  composeFooter: "Ruko only reviews content you choose to share. Never paste OTPs, PINs or passwords.",
  messageYouReceived: "A message you received",
  back: "Back",

  voiceStart: "Speak instead",
  voiceStop: "Stop and send",
  voiceCancel: "Cancel",
  voiceRecording: (seconds: number, max: number) => `Recording… ${seconds}s of ${max}s`,
  voiceSending: "Reading your voice note…",
  voiceTextAlways: "You can always type or paste instead.",
  voiceProblems: {
    unsupported: "This phone's browser can't record voice. Type or paste instead.",
    permission_denied:
      "Ruko can't use the microphone because it wasn't allowed. You can allow it in the browser settings, or type instead.",
    no_microphone: "No microphone was found. Type or paste instead.",
    too_large: "That recording is too long to send. Try a shorter one.",
    empty: "Nothing was recorded. Try again, or type instead.",
    failed: "Recording didn't work this time. Try again, or type instead.",
  } satisfies Record<RecordingProblem, string>,

  processingTitle: "Looking at what you shared…",
  processingBody: "Understanding the message and its signals.",

  clarifyEyebrow: "A quick question",
  clarifyAmountPlaceholder: "Amount in ₹",
  clarifyAmountInvalid: "Enter a whole rupee amount, like 20000.",
  clarifyNumberPlaceholder: "Number",
  clarifyNumberInvalid: "Enter a whole number, like 12.",
  clarifyNext: "Next",
  clarifySkip: "Prefer not to say",
  clarifyFooter: "Ruko asks only what it needs. Your answers stay with this decision.",

  levelEyebrow: {
    L0: "Nothing stood out",
    L1: "A small nudge",
    L2: "A moment before action",
    L3: "A deliberate pause",
  } satisfies Record<InterventionLevel, string>,
  whatISee: "What I see",
  yourContext: "Your context",
  cannotTell: "Ruko can't tell from a message alone whether an offer is genuine.",
  learnWhy: "Learn why this matters",
  thinkThrough: "Think this through",
  learn: "Learn",
  continue: "Continue",
  pauseFooterL1: "Ruko doesn't decide for you.",
  pauseFooter: "You remain in control of what happens next.",

  timerTitle: "A moment to wait",
  timerBody: (minutes: number) => `${minutes} minutes are set aside. Use them if they help.`,
  timerRemaining: (time: string) => `${time} left`,
  timerSkip: "Skip the wait",
  timerDone: "The wait is over. The choice is yours.",
  timerSkipped: "You skipped the wait. That is your call.",

  learnEyebrow: "Why this matters",
  lessonEyebrow: "A short lesson",
  lessonReadTime: (seconds: number) => `About ${seconds} seconds to read`,
  lessonTool: "Try the calculator",
  asOf: (date: string) => `As of ${date}`,
  unverified: "Not yet checked by a person",
  source: "Source",

  listen: "Listen",
  listenStop: "Stop",
  listenLoading: "Getting the voice…",
  listenBrowserVoice:
    "Ruko's voice isn't available right now, so your phone's own voice is reading this.",
  listenUnavailable: "Listening isn't available on this phone right now.",

  reflectEyebrow: "A brief reflection",
  reflectTitle: "What makes you want to do this?",
  reflectBody: "Choose what feels closest. You can keep it brief.",
  reflectChoices: [
    "Someone recommended it",
    "I'm afraid of missing out",
    "I understand the opportunity",
    "I want quick returns",
    "Something else",
  ],
  reflectOwnWords: "Or say it in your own words",
  reflectPlaceholder: "Write a thought…",
  reflectSkip: "You can also skip this step",
  reflectSkipButton: "Skip",

  decideEyebrow: "Your decision",
  decideTitle: "What will you do?",
  decideBody: "Whatever you choose is your call.",
  actions: {
    went_ahead: "Go ahead",
    delayed: "Wait for now",
    changed_amount: "Change the amount",
    dropped: "Not do it",
    set_plan: "Make a plan first",
  } satisfies Record<JournalAction, string>,
  actionPast: {
    went_ahead: "I chose to go ahead.",
    delayed: "I chose to wait.",
    changed_amount: "I chose to change the amount.",
    dropped: "I chose not to do it.",
    set_plan: "I chose to make a plan first.",
  } satisfies Record<JournalAction, string>,

  journalEyebrow: "Your journal",
  journalSavedTitle: "Decision recorded.",
  journalSavedBody: "A note for your future self.",
  whatIConsidered: "What I considered",
  why: "Why",
  myDecision: "My decision",
  journalOutro: "Your decisions stay yours. Ruko is here when you want a moment to think.",
  done: "Done",
  dontKeep: "Don't keep this note",
  journalFooter: "Journal is optional and private to you. It stays on this phone.",
  journalEmpty: "No decisions yet. When you think one through, a short note can be kept here.",
  aScreenshot: "A screenshot",
  aVoiceNote: "A voice note",
  notStated: "Not written down",
  feelingAsk: "How did that pause feel? (optional)",
  feelingHelpful: "Helpful",
  feelingFine: "Fine",
  feelingAnnoying: "Annoying",
  feelingThanks: "Thanks. Noted on this phone.",

  reportEyebrow: "What the message shows",
  nothingFound: "Nothing to report",
  glossaryEyebrow: "Explained simply",
  recoveryEyebrow: "Getting help",
  recoveryUrgent: "Do this now",
  recoveryEvidence: "Keep this evidence",
  recoveryDraft: "Draft complaint (you send it yourself)",
  recoveryTicked: (done: number, total: number) => `${done} of ${total} gathered`,
  copy: "Copy",
  copied: "Copied",
  refusalEyebrow: "Something Ruko doesn't do",
  calcEyebrow: "The arithmetic",
  calcAssumptions: "Assumptions",
  calcIllustration: "An illustration of arithmetic, not a prediction.",
  chartPutIn: "Put in",
  chartAltSeries: "A line chart of money put in and value over time, one line per assumption.",
  chartAltBars: "A bar chart of the outcome for each illustrative fall.",
  shareSomethingElse: "Share something else",
  home: "Home",
  recoveryOpen: "Get help now",

  recoverEyebrow: "If you already paid",
  recoverTitle: "Let's take this one step at a time.",
  recoverBody: "A few yes or no questions, so the steps fit what happened. Nothing here is sent to anyone.",
  recoverPaid: "Did money leave your account?",
  recoverMethod: "How did you pay?",
  recoverInstalled: "Did you install an app they sent, or share your screen?",
  recoverBroker: "Is this about your own registered broker or demat account?",
  recoverUnauthorised: "Did a trade happen in your account that you didn't place?",
  recoverCannotWithdraw: "Is a platform refusing to let you withdraw?",
  yes: "Yes",
  no: "No",
  paymentMethods: {
    upi: "UPI",
    bank_transfer: "Bank transfer",
    card: "Card",
    cash_or_other: "Cash or other",
    none: "Not applicable",
  },
  recoverSubmit: "Show me what to do",
  recoverFooter: "Ruko asks for no account numbers, OTPs or PINs, and sends nothing for you.",

  mirrorEyebrow: "My patterns",
  mirrorTitle: "What your own journal shows.",
  mirrorBody:
    "Worked out from your journal. Only the entries are sent for this view, with no notes, and nothing is kept.",
  mirrorEmpty: "Add a few decisions to your journal first. Then your patterns appear here.",
  mirrorOffline: "Patterns need a connection. Your journal itself works without one.",
  mirrorOutro: "These are your numbers, not a score. Fewer pauses is not automatically better.",
  mirrorMetrics: {
    total_decisions: "Decisions in your journal",
    unsolicited_share_pct: "Started from a group tip or an influencer",
    plans_set_pct: "Decisions with a written plan",
    pauses: "Pauses shown",
    pause_completion_pct: "Pauses you read through",
    comprehension_pct: "Pauses where you could say why they appeared",
    reconsideration_pct: "Pauses after which you changed, waited or planned",
    overrides_with_reason: "Continued past a pause, with a reason",
    overrides_without_reason: "Continued past a pause, without a reason",
  },
  mirrorWeekly: "Pauses per decision, week by week",
  mirrorWeek: (date: string) => `Week of ${date}`,
  mirrorNotEnough: "Not enough yet",

  rulesEyebrow: "My rules",
  rulesTitle: "Your commitments, on your terms.",
  rulesBody: "Optional. Saved only on this phone and sent with each check so Ruko can compare.",
  expenses: "Monthly expenses",
  savings: "Savings you can reach quickly",
  maxShare: "At most this % of my savings in one decision",
  maxAmount: "At most this many rupees in one decision",
  emergencyBuffer: "Months of expenses I want to keep untouched",
  protectedGoal: "Money set aside for a goal I won't touch (₹)",
  noBorrowed: "I don't invest borrowed money",
  coolingRule: "Minutes I want to wait before acting",
  notSet: "Not set",
  save: "Save",
  saved: "Saved on this phone",
  saveFailed: "This phone didn't allow saving.",

  settingsEyebrow: "Settings",
  settingsTitle: "Make Ruko fit you.",
  languageLabel: "Language",
  languageDraft: "Hindi and Kannada text is a draft, still waiting for native-speaker review.",
  largeText: "Large text",
  styleLabel: "How much should Ruko speak up?",
  styleQuiet: "Quiet: only the essentials",
  styleBalanced: "Balanced: a short note when something stands out",
  styleNote: "Ruko still tells you when something matters. This only trims optional extras.",
  exportTitle: "Download my anonymised summary",
  exportBody: "Counts only: no message text, no amounts, no notes. For a pilot, if you choose to share it.",
  exportButton: "Download summary",
  exportDone: "Summary downloaded.",
  demoMenu: "Demo tools",
  demoBroker: "Fictional broker demo",
  versionLine: "Ruko prototype",

  onboardEyebrow: "Welcome",
  onboardLanguageTitle: "Choose your language",
  onboardLanguageBody: "You can change it any time in Settings.",
  onboardRulesTitle: "Set your own rules, if you like.",
  onboardRulesBody:
    "Rules you write while calm are what Ruko reflects back later. All optional, and kept on this phone.",
  onboardStyleTitle: "How much should Ruko speak up?",
  onboardNext: "Next",
  onboardStart: "Start using Ruko",
  onboardSkip: "Skip, use safe defaults",
  onboardSafeDefaults:
    "Safe defaults: you have set no rules, and Ruko compares nothing with figures it made up.",

  offlineNote:
    "You are offline. Your rules, journal and checklist still work. Checking a message needs a connection.",

  errorEyebrow: "Something went wrong",
  errors: {
    backend_unavailable: "Ruko can't be reached right now. Check your connection and try again.",
    timeout: "This is taking longer than usual. Please try again.",
    invalid_response: "Ruko got an answer it couldn't read. Please try again.",
    unsupported_input: "Ruko can't read this kind of file. Try pasting the text instead.",
    reading_unavailable:
      "Ruko can't read screenshots or voice right now. Try pasting the text instead.",
    too_many_requests: "Too many checks in a short time. Wait a minute and try again.",
    invalid_request: "Ruko couldn't use that input. Try pasting the message again.",
    server_error: "Something went wrong on Ruko's side. Please try again.",
  } satisfies Record<AppErrorKind, string>,
  tryAgain: "Try again",
  startOver: "Start over",
};

export type Copy = typeof en;
