// English chrome text (buttons, labels, empty and error states). Everything Ruko *says about
// a decision* comes from the backend's rendered templates instead. Hindi and Kannada live in
// hi.ts and kn.ts and must define every key here (the compiler checks), as drafts for native review.

import type { AppErrorKind } from "../services/api";
import type { RecordingProblem } from "../services/recorder";
import type { InterventionLevel, JournalAction } from "../types/api";

export const en = {
  privateByDesign: "Private by design",
  homeEyebrow: "Your decision space",
  homeTitle: "Before you act, take a moment.",
  homeBody:
    "A calm place to think through a financial decision. Ruko helps you pause; the choice stays yours.",
  shareSomething: "Share something",
  shareHint: "Bring in only what you choose to share.",
  thinkDecision: "Think through a decision",
  myRules: "My rules",
  myRulesHint: "Your commitments, on your terms",
  journal: "Journal",
  journalHint: "Look back at a decision",
  homeFooter: "Only what you share is analyzed · No broker, OTP or SMS access",
  workOutNumber: "Work out a number",
  workOutNumberHint: "A SIP, a goal, a fall in value",
  alreadyPaid: "I already paid",
  alreadyPaidHint: "Step-by-step help, in order",
  myPatterns: "My patterns",
  myPatternsHint: "What your own journal shows",
  settings: "Settings",
  settingsHint: "Language, text size, how much Ruko speaks",

  composeEyebrow: "Shared with Ruko",
  composeDecisionEyebrow: "Think through a decision",
  composeLabel: "Paste the message you received",
  composeDecisionLabel: "What are you thinking of doing?",
  composePlaceholder: "Paste or type the message here",
  composeAddScreenshot: "Add a screenshot instead",
  composeRemoveScreenshot: "Remove screenshot",
  composeScreenshotChosen: "Screenshot added",
  composeSubmit: "Look at this",
  composeEmpty: "Paste a message or add a screenshot first.",
  composeFooter: "Ruko only reviews content you choose to share. Never paste OTPs, PINs or passwords.",
  messageYouReceived: "A message you received",
  back: "Back",

  voiceStart: "Speak instead",
  voiceStop: "Stop and send",
  voiceCancel: "Cancel",
  voiceRecording: (seconds: number, max: number) => `Recording… ${seconds}s of ${max}s`,
  voiceSending: "Reading your voice note…",
  voiceTextAlways: "You can always type or paste instead.",
  voiceProblems: {
    unsupported: "This phone's browser can't record voice. Type or paste instead.",
    permission_denied:
      "Ruko can't use the microphone because it wasn't allowed. You can allow it in the browser settings, or type instead.",
    no_microphone: "No microphone was found. Type or paste instead.",
    too_large: "That recording is too long to send. Try a shorter one.",
    empty: "Nothing was recorded. Try again, or type instead.",
    failed: "Recording didn't work this time. Try again, or type instead.",
  } satisfies Record<RecordingProblem, string>,

  processingTitle: "Looking at what you shared…",
  processingBody: "Understanding the message and its signals.",

  clarifyEyebrow: "A quick question",
  clarifyAmountPlaceholder: "Amount in ₹",
  clarifyAmountInvalid: "Enter a whole rupee amount, like 20000.",
  clarifyNumberPlaceholder: "Number",
  clarifyNumberInvalid: "Enter a whole number, like 12.",
  clarifyNext: "Next",
  clarifySkip: "Prefer not to say",
  clarifyFooter: "Ruko asks only what it needs. Your answers stay with this decision.",

  levelEyebrow: {
    L0: "Nothing stood out",
    L1: "A small nudge",
    L2: "A moment before action",
    L3: "A deliberate pause",
  } satisfies Record<InterventionLevel, string>,
  whatISee: "What I see",
  yourContext: "Your context",
  cannotTell: "Ruko can't tell from a message alone whether an offer is genuine.",
  learnWhy: "Learn why this matters",
  thinkThrough: "Think this through",
  learn: "Learn",
  continue: "Continue",
  pauseFooterL1: "Ruko doesn't decide for you.",
  pauseFooter: "You remain in control of what happens next.",

  timerTitle: "A moment to wait",
  timerBody: (minutes: number) => `${minutes} minutes are set aside. Use them if they help.`,
  timerRemaining: (time: string) => `${time} left`,
  timerSkip: "Skip the wait",
  timerDone: "The wait is over. The choice is yours.",
  timerSkipped: "You skipped the wait. That is your call.",

  learnEyebrow: "Why this matters",
  lessonEyebrow: "A short lesson",
  lessonReadTime: (seconds: number) => `About ${seconds} seconds to read`,
  lessonTool: "Try the calculator",
  stepSee: "See",
  stepThink: "Think",
  stepDecide: "Decide",
  stepsLabel: "Where you are in this decision",
  moneyThisDecision: "This decision",
  moneyOfSavings: "of your savings",
  moneyMonths: "months of your expenses",
  moneyAbout: "about",
  moneyYourSavings: "Your savings",
  moneyLeft: (amount: string, approx: boolean) => `${approx ? "about " : ""}${amount} would be left`,
  moneyInWords: "Your numbers in words",
  movesTitle: "If the price moves against you (arithmetic, not a forecast)",
  moveLine: (pct: string) => `${pct}% move`,
  movesNote: "The dashed line is the money you put in. A bar past it means losing more than that.",
  shortsNext: "Next",
  shortsHint: "Swipe up for the next card",
  shortsEndTitle: "You're ready to decide",
  shortsEndBody: "That's all this decision needs. The choice is yours.",
  shortsLessonDone: "Lesson done",
  calcMineLast: (amount: string) => `My last decision: ${amount}`,
  calcMineGoal: (amount: string) => `My goal: ${amount}`,
  calcMinePlan: (amount: string) => `My plan: up to ${amount}`,
  calcYears: (years: number) => (years === 1 ? "1 year" : `${years} years`),
  greetMorning: "Good morning",
  greetAfternoon: "Good afternoon",
  greetEvening: "Good evening",
  snapshotTitle: "Your Ruko so far",
  snapshotRules: "rules of your own",
  snapshotDecisions: "decisions this week",
  snapshotLessons: "lessons read",
  lessonOwnGuidance: "General guidance from Ruko, not from an official source.",
  learnTile: "Learn",
  learnTileHint: "Short lessons in plain words",
  learnHubIntro:
    "Short lessons in plain words, for anyone. Tap a highlighted word anywhere in Ruko to see what it means.",
  learnProgress: (read: number, total: number) => `${read} of ${total} read`,
  learnFeatured: "Next for you",
  learnRead: "Read this lesson",
  learnReadAgain: "Read again",
  learnAllRead: "You have read every lesson. Open any of them to read it again.",
  learnEmpty: "Lessons will appear here once a person has checked them.",
  learnWords: "Words you will hear",
  learnWordsHint: "Tap a word for a short explanation.",
  learnLoading: "Getting the lessons…",
  learnSeen: "Read",
  lessonNext: "Read next",
  lessonBackToLearn: "Back to Learn",
  lessonBack: "Back",
  termMore: "Full explanation",
  termClose: "Close",
  learnNextTitle: "Worth knowing",
  homeLearnTitle: "A lesson for you",
  asOf: (date: string) => `As of ${date}`,
  unverified: "Not yet checked by a person",
  source: "Source",

  listen: "Listen",
  listenStop: "Stop",
  listenLoading: "Getting the voice…",
  listenBrowserVoice:
    "Ruko's voice isn't available right now, so your phone's own voice is reading this.",
  listenUnavailable: "Listening isn't available on this phone right now.",

  reflectEyebrow: "A brief reflection",
  reflectTitle: "What makes you want to do this?",
  reflectBody: "Choose what feels closest. You can keep it brief.",
  reflectChoices: [
    "Someone recommended it",
    "I'm afraid of missing out",
    "I understand the opportunity",
    "I want quick returns",
    "Something else",
  ],
  reflectOwnWords: "Or say it in your own words",
  reflectPlaceholder: "Write a thought…",
  reflectSkip: "You can also skip this step",
  reflectSkipButton: "Skip",

  decideEyebrow: "Your decision",
  decideTitle: "What will you do?",
  decideBody: "Whatever you choose is your call.",
  actions: {
    went_ahead: "Go ahead",
    delayed: "Wait for now",
    changed_amount: "Change the amount",
    dropped: "Not do it",
    set_plan: "Make a plan first",
  } satisfies Record<JournalAction, string>,
  actionPast: {
    went_ahead: "I chose to go ahead.",
    delayed: "I chose to wait.",
    changed_amount: "I chose to change the amount.",
    dropped: "I chose not to do it.",
    set_plan: "I chose to make a plan first.",
  } satisfies Record<JournalAction, string>,

  journalEyebrow: "Your journal",
  journalSavedTitle: "Decision recorded.",
  journalSavedBody: "A note for your future self.",
  whatIConsidered: "What I considered",
  why: "Why",
  myDecision: "My decision",
  journalOutro: "Your decisions stay yours. Ruko is here when you want a moment to think.",
  done: "Done",
  dontKeep: "Don't keep this note",
  journalFooter: "Journal is optional and private to you. It stays on this phone.",
  journalEmpty: "No decisions yet. When you think one through, a short note can be kept here.",
  aScreenshot: "A screenshot",
  aVoiceNote: "A voice note",
  notStated: "Not written down",
  feelingAsk: "How did that pause feel? (optional)",
  feelingHelpful: "Helpful",
  feelingFine: "Fine",
  feelingAnnoying: "Annoying",
  feelingThanks: "Thanks. Noted on this phone.",

  reportEyebrow: "What the message shows",
  nothingFound: "Nothing to report",
  glossaryEyebrow: "Explained simply",
  recoveryEyebrow: "Getting help",
  recoveryUrgent: "Do this now",
  recoveryEvidence: "Keep this evidence",
  recoveryDraft: "Draft complaint (you send it yourself)",
  recoveryTicked: (done: number, total: number) => `${done} of ${total} gathered`,
  copy: "Copy",
  copied: "Copied",
  refusalEyebrow: "Something Ruko doesn't do",
  calcEyebrow: "The arithmetic",
  calcAssumptions: "Assumptions",
  calcIllustration: "An illustration of arithmetic, not a prediction.",
  chartPutIn: "Put in",
  chartAltSeries: "A line chart of money put in and value over time, one line per assumption.",
  chartAltBars: "A bar chart of the outcome for each illustrative fall.",
  shareSomethingElse: "Share something else",
  home: "Home",
  recoveryOpen: "Get help now",

  recoverEyebrow: "If you already paid",
  recoverTitle: "Let's take this one step at a time.",
  recoverBody: "A few yes or no questions, so the steps fit what happened. Nothing here is sent to anyone.",
  recoverPaid: "Did money leave your account?",
  recoverMethod: "How did you pay?",
  recoverInstalled: "Did you install an app they sent, or share your screen?",
  recoverBroker: "Is this about your own registered broker or demat account?",
  recoverUnauthorised: "Did a trade happen in your account that you didn't place?",
  recoverCannotWithdraw: "Is a platform refusing to let you withdraw?",
  yes: "Yes",
  no: "No",
  paymentMethods: {
    upi: "UPI",
    bank_transfer: "Bank transfer",
    card: "Card",
    cash_or_other: "Cash or other",
    none: "Not applicable",
  },
  recoverSubmit: "Show me what to do",
  recoverFooter: "Ruko asks for no account numbers, OTPs or PINs, and sends nothing for you.",

  mirrorEyebrow: "My patterns",
  mirrorTitle: "What your own journal shows.",
  mirrorBody:
    "Worked out from your journal. Only the entries are sent for this view, with no notes, and nothing is kept.",
  mirrorEmpty: "Add a few decisions to your journal first. Then your patterns appear here.",
  mirrorOffline: "Patterns need a connection. Your journal itself works without one.",
  mirrorOutro: "These are your numbers, not a score. Fewer pauses is not automatically better.",
  mirrorMetrics: {
    total_decisions: "Decisions in your journal",
    unsolicited_share_pct: "Started from a group tip or an influencer",
    plans_set_pct: "Decisions with a written plan",
    pauses: "Pauses shown",
    pause_completion_pct: "Pauses you read through",
    comprehension_pct: "Pauses where you could say why they appeared",
    reconsideration_pct: "Pauses after which you changed, waited or planned",
    overrides_with_reason: "Continued past a pause, with a reason",
    overrides_without_reason: "Continued past a pause, without a reason",
  },
  mirrorWeekly: "Pauses per decision, week by week",
  mirrorWeek: (date: string) => `Week of ${date}`,
  mirrorNotEnough: "Not enough yet",

  rulesEyebrow: "My rules",
  rulesTitle: "Your commitments, on your terms.",
  rulesBody: "Optional. Saved only on this phone and sent with each check so Ruko can compare.",
  expenses: "Monthly expenses",
  savings: "Savings you can reach quickly",
  maxShare: "At most this % of my savings in one decision",
  maxAmount: "At most this many rupees in one decision",
  emergencyBuffer: "Months of expenses I want to keep untouched",
  protectedGoal: "Money set aside for a goal I won't touch (₹)",
  noBorrowed: "I don't invest borrowed money",
  coolingRule: "Minutes I want to wait before acting",
  notSet: "Not set",
  save: "Save",
  saved: "Saved on this phone",
  saveFailed: "This phone didn't allow saving.",

  settingsEyebrow: "Settings",
  settingsTitle: "Make Ruko fit you.",
  languageLabel: "Language",
  languageDraft: "Hindi and Kannada text is a draft, still waiting for native-speaker review.",
  largeText: "Large text",
  styleLabel: "How much should Ruko speak up?",
  styleQuiet: "Quiet: only the essentials",
  styleBalanced: "Balanced: a short note when something stands out",
  styleNote: "Ruko still tells you when something matters. This only trims optional extras.",
  exportTitle: "Download my anonymised summary",
  exportBody: "Counts only: no message text, no amounts, no notes. For a pilot, if you choose to share it.",
  exportButton: "Download summary",
  exportDone: "Summary downloaded.",
  demoMenu: "Demo tools",
  demoBroker: "Fictional broker demo",
  versionLine: "Ruko prototype",

  onboardEyebrow: "Welcome",
  onboardLanguageTitle: "Choose your language",
  onboardLanguageBody: "You can change it any time in Settings.",
  onboardRulesTitle: "Set your own rules, if you like.",
  onboardRulesBody:
    "Rules you write while calm are what Ruko reflects back later. All optional, and kept on this phone.",
  onboardStyleTitle: "How much should Ruko speak up?",
  onboardNext: "Next",
  onboardStart: "Start using Ruko",
  onboardSkip: "Skip, use safe defaults",
  onboardSafeDefaults:
    "Safe defaults: you have set no rules, and Ruko compares nothing with figures it made up.",


  // --- Adaptive questions, refine, quotes, plans, calculator, home (A to F) ---
  clarifyContinue: "Continue",
  clarifyChooseOne: "Choose one.",
  clarifyAnswerAfterSkip: "Answer after all",
  lastTime: "Last time",
  aboutYouTitle: "A little about you (optional)",
  aboutYouNote: "Asked once and kept on this phone. It only helps Ruko compare.",
  experienceQuestion: "How familiar is this kind of decision to you?",
  experienceOptions: {
    none: "New to me",
    some: "I've done it a few times",
    regular: "I do this regularly",
  },
  recentLossQuestion: "Have you taken a loss recently?",
  recentLossOptions: { yes: "Yes, recently", no: "No" },
  tradesQuestion: "How many trades have you made this week?",
  tradesOptions: { "0": "None", "1_5": "1 to 5", "6_20": "6 to 20", gt_20: "More than 20" },

  refineTitle: "Make this about your money",
  refineBody: "Add your own numbers and Ruko will show what this means for you.",
  refineButton: "Show what this means for me",

  yourMessageTitle: "Your message, with what Ruko noticed",
  fromYourMessage: "From your message",
  showMessage: "Show my message",
  hideMessage: "Hide my message",

  reflectByReason: {
    UNSOLICITED_SOURCE: "Someone I don't know sent it",
    URGENCY_PRESSURE: "The deadline is pushing me",
    GUARANTEED_RETURN_CLAIM: "The promised return is tempting",
    PROFIT_SCREENSHOT_SOCIAL_PROOF: "Others seem to be making money",
    AUTHORITY_CLAIM: "They sound like they know best",
    POST_LOSS_REENTRY_DECLARED: "I want to win back an earlier loss",
    LATE_NIGHT_DECISION: "It's late and I want this settled now",
    HIGH_FREQUENCY_DECLARED: "I enjoy trading actively",
    FIRST_TIME_PRODUCT: "I'm curious to try something new",
  } as Record<string, string>,
  reflectFomo: "I'm afraid of missing out",
  reflectTrusted: "Someone I trust recommended it",
  reflectUnderstand: "I understand it and have thought it through",
  reflectOther: "Something else",
  decideNow: "Decide",
  reflectOptional: "Add a reason first (optional)",
  paceNote: "You usually skip the reflection step, so Ruko skips it for you. You can still add a reason.",
  changeAmountTitle: "What amount would you like to check instead?",
  changeAmountButton: "Check this amount",
  amountPlaceholder: "Amount in ₹",
  planAddedNote: "Plan added. Ruko checked again with it.",

  planEyebrow: "Your plan",
  planTitle: "Write your own plan, in your words.",
  planBody:
    "The words stay on this phone. Ruko only learns which parts you wrote, so it can tell whether the plan is complete.",
  planReason: "Why am I doing this?",
  planHorizon: "How long do I mean to stay in?",
  planHorizonOptions: {
    days: "A few days",
    weeks: "A few weeks",
    months: "A few months",
    years: "Years",
    unsure: "Not sure yet",
  },
  planReconsider: "What would make me reconsider, or get out?",
  planRangeTitle: "Amount range for this plan (optional)",
  planFrom: "From ₹",
  planTo: "To ₹",
  planSave: "Keep it as a plan for this kind of decision",
  planSubmit: "Use this plan",
  planEmpty: "Write at least one part of your plan: why, how long, or what would make you reconsider.",
  planRangeInvalid: "Give both amounts as whole rupees, with the first not above the second.",
  plansTitle: "My plans",
  plansEmpty: "No plans yet. You can write one when a decision comes up.",
  planRemove: "Remove",
  planRange: (min: string, max: string) => `${min} to ${max}`,

  calcToolTitle: "Try your own numbers",
  calcToolBody: "Change any number and the result updates. It is arithmetic under your assumptions, not a prediction.",
  calcTools: {
    sip: "A SIP",
    goal: "A goal",
    inflation: "Inflation",
    consequence: "A fall in value",
    costs: "Trading costs",
  },
  calcFields: {
    monthly_inr: "Monthly amount (₹)",
    months: "Number of months",
    goal_inr: "Goal amount (₹)",
    already_saved_inr: "Already saved (₹, optional)",
    amount_inr: "Amount (₹)",
    years: "Number of years",
    leverage: "Leverage, in times (1 means none)",
    trade_value_inr: "Value of one trade (₹)",
    trades_per_month: "Trades in a month",
  },
  calcRates: "Yearly rates to try (%)",
  calcDrops: "Falls to try (%)",
  calcAddRate: "Add",
  calcRatePlaceholder: "For example 8",
  calcRateNote: "Your own rates sit next to Ruko's labelled example rates.",
  calcRemove: (value: string) => `Remove ${value}`,
  calcUpdating: "Updating…",
  calcFillIn: "Fill in the numbers above to see the result.",
  calcAdjust: "Adjust these numbers",

  waitDueTitle: "Your wait is over",
  waitPendingTitle: "You chose to wait",
  waitDueBody: "Still thinking about it? It is your call either way.",
  waitPendingBody: "Ruko will ask again when your wait is over.",
  waitLookAgain: "Look at it again",
  waitLetGo: "I've let it go",
  planFollowTitle: "Did you follow your plan?",
  planFollowBody: (date: string) => `You wrote a plan on ${date}.`,
  planYes: "Yes",
  planNo: "Not this time",
  planNotYet: "Not yet",
  homeBack: "Welcome back.",
  notNow: "Not now",
  moneyCheckText: "Thinking of making an investment",
  homeRulesNudgeTitle: "Set one rule of your own",
  homeRulesNudgeBody: "When you decide calmly, Ruko can hold you to it later.",
  homeRulesNudgeButton: "Set a rule",
  homePatternsNudgeTitle: "See what your journal shows",
  homePatternsNudgeBody: "You have a few decisions on record.",
  bridgeMoney: "Show what an amount would mean for my money",
  bridgeMoneyNote:
    "Ruko can't say whether to buy it, but it can show what an amount would mean for your savings and your rules.",
  bridgeFall: "See what a fall would mean in rupees",
  bridgeFallNote: "Nobody can say what will happen, but the arithmetic of a fall is just maths.",
  glossaryMore: "More terms Ruko can explain",
  profileExperience: "How familiar I am with each (optional)",
  ageBandLabel: "My age (optional)",
  ageBands: {
    lt_30: "Under 30",
    "30_40": "30 to 40",
    "40_50": "40 to 50",
    "50_60": "50 to 60",
    gt_60: "Over 60",
  },
  productNames: {
    cash_equity: "Company shares",
    derivative: "Futures or options (F&O)",
    ipo: "An IPO",
    mutual_fund: "A mutual fund",
    crypto: "Crypto",
  },

  offlineNote:
    "You are offline. Your rules, journal and checklist still work. Checking a message needs a connection.",

  errorEyebrow: "Something went wrong",
  errors: {
    backend_unavailable: "Ruko can't be reached right now. Check your connection and try again.",
    timeout: "This is taking longer than usual. Please try again.",
    invalid_response: "Ruko got an answer it couldn't read. Please try again.",
    unsupported_input: "Ruko can't read this kind of file. Try pasting the text instead.",
    reading_unavailable:
      "Ruko can't read screenshots or voice right now. Try pasting the text instead.",
    too_many_requests: "Too many checks in a short time. Wait a minute and try again.",
    invalid_request: "Ruko couldn't use that input. Try pasting the message again.",
    server_error: "Something went wrong on Ruko's side. Please try again.",
  } satisfies Record<AppErrorKind, string>,
  tryAgain: "Try again",
  startOver: "Start over",
};

export type Copy = typeof en;
