// Hindi chrome text. DRAFT: every string here awaits native-speaker review (see status.ts).

import type { Copy } from "./en";

export const hi: Copy = {
  privateByDesign: "डिज़ाइन से ही निजी",
  homeEyebrow: "आपका फ़ैसले का स्थान",
  homeTitle: "कुछ करने से पहले, एक पल रुकिए।",
  homeBody:
    "पैसों से जुड़े फ़ैसले को शांति से सोचने की जगह। Ruko आपको रुकने में मदद करता है; फ़ैसला आपका ही रहता है।",
  shareSomething: "कुछ साझा करें",
  shareHint: "सिर्फ़ वही लाएँ जो आप साझा करना चाहें।",
  thinkDecision: "किसी फ़ैसले पर सोचें",
  myRules: "मेरे नियम",
  myRulesHint: "आपकी प्रतिबद्धताएँ, आपकी शर्तों पर",
  journal: "डायरी",
  journalHint: "पिछला फ़ैसला देखें",
  homeFooter: "सिर्फ़ वही जाँचा जाता है जो आप साझा करें · ब्रोकर, OTP या SMS तक कोई पहुँच नहीं",
  workOutNumber: "कोई संख्या निकालें",
  workOutNumberHint: "SIP, लक्ष्य, कीमत में गिरावट",
  alreadyPaid: "मैं पैसे दे चुका/चुकी हूँ",
  alreadyPaidHint: "क्रम से, कदम-दर-कदम मदद",
  myPatterns: "मेरे पैटर्न",
  myPatternsHint: "आपकी अपनी डायरी क्या दिखाती है",
  settings: "सेटिंग्स",
  settingsHint: "भाषा, अक्षरों का आकार, Ruko कितना बोले",

  composeEyebrow: "Ruko के साथ साझा",
  composeDecisionEyebrow: "किसी फ़ैसले पर सोचें",
  composeCalcEyebrow: "कोई संख्या निकालें",
  composeLabel: "जो मैसेज मिला उसे यहाँ चिपकाएँ",
  composeDecisionLabel: "आप क्या करने की सोच रहे हैं?",
  composeCalcLabel: "आप क्या निकालना चाहते हैं?",
  composeCalcExample: "उदाहरण: 10 साल तक हर महीने 5000 की SIP",
  composePlaceholder: "मैसेज यहाँ चिपकाएँ या लिखें",
  composeAddScreenshot: "इसकी जगह स्क्रीनशॉट जोड़ें",
  composeRemoveScreenshot: "स्क्रीनशॉट हटाएँ",
  composeScreenshotChosen: "स्क्रीनशॉट जोड़ा गया",
  composeSubmit: "इसे देखें",
  composeEmpty: "पहले कोई मैसेज चिपकाएँ या स्क्रीनशॉट जोड़ें।",
  composeFooter:
    "Ruko सिर्फ़ वही देखता है जो आप साझा करें। OTP, PIN या पासवर्ड कभी न चिपकाएँ।",
  messageYouReceived: "आपको मिला एक मैसेज",
  back: "वापस",

  voiceStart: "बोलकर बताएँ",
  voiceStop: "रोकें और भेजें",
  voiceCancel: "रद्द करें",
  voiceRecording: (seconds: number, max: number) => `रिकॉर्डिंग… ${max} में से ${seconds} सेकंड`,
  voiceSending: "आपका वॉइस नोट पढ़ा जा रहा है…",
  voiceTextAlways: "आप हमेशा लिखकर या चिपकाकर भी बता सकते हैं।",
  voiceProblems: {
    unsupported: "इस फ़ोन का ब्राउज़र आवाज़ रिकॉर्ड नहीं कर सकता। लिखें या चिपकाएँ।",
    permission_denied:
      "माइक्रोफ़ोन की अनुमति नहीं मिली, इसलिए Ruko उसे इस्तेमाल नहीं कर सकता। आप ब्राउज़र सेटिंग्स में अनुमति दे सकते हैं, या लिखकर बता सकते हैं।",
    no_microphone: "कोई माइक्रोफ़ोन नहीं मिला। लिखें या चिपकाएँ।",
    too_large: "यह रिकॉर्डिंग भेजने के लिए बहुत बड़ी है। छोटी रिकॉर्डिंग आज़माएँ।",
    empty: "कुछ रिकॉर्ड नहीं हुआ। फिर कोशिश करें, या लिखकर बताएँ।",
    failed: "इस बार रिकॉर्डिंग नहीं हो पाई। फिर कोशिश करें, या लिखकर बताएँ।",
  },

  processingTitle: "आपने जो साझा किया उसे देख रहे हैं…",
  processingBody: "मैसेज और उसके संकेतों को समझ रहे हैं।",

  clarifyEyebrow: "एक छोटा सवाल",
  clarifyAmountPlaceholder: "रकम ₹ में",
  clarifyAmountInvalid: "पूरी रुपये की रकम लिखें, जैसे 20000।",
  clarifyNumberPlaceholder: "संख्या",
  clarifyNumberInvalid: "पूरी संख्या लिखें, जैसे 12।",
  clarifyNext: "आगे",
  clarifySkip: "बताना नहीं चाहता/चाहती",
  clarifyFooter: "Ruko सिर्फ़ वही पूछता है जो ज़रूरी है। आपके जवाब इसी फ़ैसले तक रहते हैं।",

  levelEyebrow: {
    L0: "कुछ खास नहीं दिखा",
    L1: "एक हल्का इशारा",
    L2: "कदम उठाने से पहले एक पल",
    L3: "सोच-समझकर रुकना",
  },
  whatISee: "मुझे क्या दिखता है",
  yourContext: "आपकी स्थिति",
  cannotTell: "सिर्फ़ मैसेज देखकर Ruko यह नहीं बता सकता कि कोई ऑफ़र असली है या नहीं।",
  learnWhy: "जानें यह क्यों मायने रखता है",
  thinkThrough: "इस पर सोचें",
  learn: "जानें",
  continue: "आगे बढ़ें",
  pauseFooterL1: "Ruko आपके लिए फ़ैसला नहीं करता।",
  pauseFooter: "आगे क्या होगा, यह आपके हाथ में रहता है।",

  timerTitle: "रुकने का एक पल",
  timerBody: (minutes: number) => `${minutes} मिनट अलग रखे गए हैं। काम आएँ तो इस्तेमाल करें।`,
  timerRemaining: (time: string) => `${time} बाकी`,
  timerSkip: "इंतज़ार छोड़ें",
  timerDone: "इंतज़ार पूरा हुआ। फ़ैसला आपका है।",
  timerSkipped: "आपने इंतज़ार छोड़ दिया। यह आपका फ़ैसला है।",

  learnEyebrow: "यह क्यों मायने रखता है",
  lessonEyebrow: "एक छोटा पाठ",
  lessonReadTime: (seconds: number) => `पढ़ने में करीब ${seconds} सेकंड`,
  lessonTool: "कैलकुलेटर आज़माएँ",
  asOf: (date: string) => `${date} तक की जानकारी`,
  unverified: "अभी किसी व्यक्ति ने जाँचा नहीं है",
  source: "स्रोत",

  listen: "सुनें",
  listenStop: "रोकें",
  listenLoading: "आवाज़ ला रहे हैं…",
  listenBrowserVoice: "अभी Ruko की आवाज़ उपलब्ध नहीं है, इसलिए आपके फ़ोन की अपनी आवाज़ इसे पढ़ रही है।",
  listenUnavailable: "इस फ़ोन पर अभी सुनना उपलब्ध नहीं है।",

  reflectEyebrow: "एक छोटा विचार",
  reflectTitle: "आप यह क्यों करना चाहते हैं?",
  reflectBody: "जो सबसे करीब लगे उसे चुनें। संक्षेप में भी चलेगा।",
  reflectChoices: [
    "किसी ने सुझाया",
    "कुछ छूट जाने का डर है",
    "मैं इस मौके को समझता/समझती हूँ",
    "मुझे जल्दी रिटर्न चाहिए",
    "कुछ और",
  ],
  reflectOwnWords: "या अपने शब्दों में लिखें",
  reflectPlaceholder: "एक विचार लिखें…",
  reflectSkip: "आप यह चरण छोड़ भी सकते हैं",
  reflectSkipButton: "छोड़ें",

  decideEyebrow: "आपका फ़ैसला",
  decideTitle: "आप क्या करेंगे?",
  decideBody: "जो भी चुनें, वह आपका फ़ैसला है।",
  actions: {
    went_ahead: "आगे बढ़ूँगा/बढ़ूँगी",
    delayed: "अभी रुकूँगा/रुकूँगी",
    changed_amount: "रकम बदलूँगा/बदलूँगी",
    dropped: "नहीं करूँगा/करूँगी",
    set_plan: "पहले योजना बनाऊँगा/बनाऊँगी",
  },
  actionPast: {
    went_ahead: "मैंने आगे बढ़ने का फ़ैसला किया।",
    delayed: "मैंने रुकने का फ़ैसला किया।",
    changed_amount: "मैंने रकम बदलने का फ़ैसला किया।",
    dropped: "मैंने इसे न करने का फ़ैसला किया।",
    set_plan: "मैंने पहले योजना बनाने का फ़ैसला किया।",
  },

  journalEyebrow: "आपकी डायरी",
  journalSavedTitle: "फ़ैसला दर्ज हो गया।",
  journalSavedBody: "आपके भविष्य के लिए एक नोट।",
  whatIConsidered: "मैंने क्या देखा",
  why: "क्यों",
  myDecision: "मेरा फ़ैसला",
  journalOutro: "आपके फ़ैसले आपके ही रहते हैं। जब आप सोचने के लिए एक पल चाहें, Ruko यहीं है।",
  done: "हो गया",
  dontKeep: "यह नोट न रखें",
  journalFooter: "डायरी वैकल्पिक है और सिर्फ़ आपकी है। यह इसी फ़ोन में रहती है।",
  journalEmpty: "अभी कोई फ़ैसला नहीं। जब आप किसी पर सोचेंगे, तो यहाँ एक छोटा नोट रखा जा सकता है।",
  aScreenshot: "एक स्क्रीनशॉट",
  aVoiceNote: "एक वॉइस नोट",
  notStated: "लिखा नहीं गया",
  feelingAsk: "वह ठहराव कैसा लगा? (वैकल्पिक)",
  feelingHelpful: "मददगार",
  feelingFine: "ठीक",
  feelingAnnoying: "परेशान करने वाला",
  feelingThanks: "धन्यवाद। इसी फ़ोन में दर्ज हो गया।",

  reportEyebrow: "मैसेज क्या दिखाता है",
  nothingFound: "बताने लायक कुछ नहीं",
  glossaryEyebrow: "आसान शब्दों में",
  recoveryEyebrow: "मदद पाना",
  recoveryUrgent: "यह अभी करें",
  recoveryEvidence: "ये सबूत सँभालकर रखें",
  recoveryDraft: "शिकायत का मसौदा (इसे आप खुद भेजें)",
  recoveryTicked: (done: number, total: number) => `${total} में से ${done} जुटाए`,
  copy: "कॉपी करें",
  copied: "कॉपी हो गया",
  refusalEyebrow: "जो Ruko नहीं करता",
  calcEyebrow: "गणित",
  calcAssumptions: "मान्यताएँ",
  calcIllustration: "यह गणित का एक उदाहरण है, कोई अनुमान नहीं।",
  chartPutIn: "लगाया गया",
  chartAltSeries: "समय के साथ लगाई गई रकम और मूल्य का लाइन चार्ट, हर मान्यता की एक लाइन।",
  chartAltBars: "हर काल्पनिक गिरावट के नतीजे का बार चार्ट।",
  shareSomethingElse: "कुछ और साझा करें",
  home: "होम",
  recoveryOpen: "अभी मदद लें",

  recoverEyebrow: "अगर आप पैसे दे चुके हैं",
  recoverTitle: "एक-एक कदम करके चलते हैं।",
  recoverBody: "कुछ हाँ-ना वाले सवाल, ताकि कदम आपकी स्थिति से मेल खाएँ। यहाँ से कुछ भी किसी को नहीं भेजा जाता।",
  recoverPaid: "क्या आपके खाते से पैसे गए?",
  recoverMethod: "आपने भुगतान कैसे किया?",
  recoverInstalled: "क्या आपने उनका भेजा ऐप इंस्टॉल किया, या अपनी स्क्रीन साझा की?",
  recoverBroker: "क्या यह आपके अपने पंजीकृत ब्रोकर या डीमैट खाते से जुड़ा है?",
  recoverUnauthorised: "क्या आपके खाते में ऐसा ट्रेड हुआ जो आपने नहीं किया?",
  recoverCannotWithdraw: "क्या कोई प्लेटफ़ॉर्म आपको पैसे निकालने नहीं दे रहा?",
  yes: "हाँ",
  no: "नहीं",
  paymentMethods: {
    upi: "UPI",
    bank_transfer: "बैंक ट्रांसफ़र",
    card: "कार्ड",
    cash_or_other: "नकद या अन्य",
    none: "लागू नहीं",
  },
  recoverSubmit: "मुझे बताएँ क्या करना है",
  recoverFooter: "Ruko खाता नंबर, OTP या PIN नहीं माँगता, और आपकी ओर से कुछ भेजता नहीं।",

  mirrorEyebrow: "मेरे पैटर्न",
  mirrorTitle: "आपकी अपनी डायरी क्या दिखाती है।",
  mirrorBody:
    "आपकी डायरी से निकाला गया। इस दृश्य के लिए सिर्फ़ प्रविष्टियाँ भेजी जाती हैं, नोट नहीं, और कुछ भी रखा नहीं जाता।",
  mirrorEmpty: "पहले अपनी डायरी में कुछ फ़ैसले जोड़ें। फिर आपके पैटर्न यहाँ दिखेंगे।",
  mirrorOffline: "पैटर्न देखने के लिए कनेक्शन चाहिए। आपकी डायरी बिना कनेक्शन के भी चलती है।",
  mirrorOutro: "ये आपकी अपनी संख्याएँ हैं, कोई स्कोर नहीं। कम ठहराव का मतलब अपने-आप बेहतर नहीं होता।",
  mirrorMetrics: {
    total_decisions: "डायरी में फ़ैसले",
    unsolicited_share_pct: "ग्रुप टिप या इन्फ़्लुएंसर से शुरू हुए",
    plans_set_pct: "लिखित योजना वाले फ़ैसले",
    pauses: "दिखाए गए ठहराव",
    pause_completion_pct: "जो ठहराव आपने पूरे पढ़े",
    comprehension_pct: "जहाँ आप बता सके कि ठहराव क्यों आया",
    reconsideration_pct: "ठहराव के बाद जहाँ आपने बदला, रुके या योजना बनाई",
    overrides_with_reason: "ठहराव के बावजूद आगे बढ़े, कारण के साथ",
    overrides_without_reason: "ठहराव के बावजूद आगे बढ़े, बिना कारण",
  },
  mirrorWeekly: "हर फ़ैसले पर ठहराव, हफ़्ते-दर-हफ़्ते",
  mirrorWeek: (date: string) => `${date} वाला हफ़्ता`,
  mirrorNotEnough: "अभी काफ़ी नहीं",

  rulesEyebrow: "मेरे नियम",
  rulesTitle: "आपकी प्रतिबद्धताएँ, आपकी शर्तों पर।",
  rulesBody: "वैकल्पिक। सिर्फ़ इसी फ़ोन में सहेजे जाते हैं और हर जाँच के साथ भेजे जाते हैं ताकि Ruko तुलना कर सके।",
  expenses: "मासिक खर्च",
  savings: "बचत जो जल्दी मिल सके",
  maxShare: "एक फ़ैसले में अपनी बचत का ज़्यादा से ज़्यादा इतना %",
  maxAmount: "एक फ़ैसले में ज़्यादा से ज़्यादा इतने रुपये",
  emergencyBuffer: "खर्च के कितने महीने मैं अछूते रखना चाहता/चाहती हूँ",
  protectedGoal: "किसी लक्ष्य के लिए अलग रखा पैसा जिसे मैं नहीं छुऊँगा/छुऊँगी (₹)",
  noBorrowed: "मैं उधार के पैसे नहीं लगाता/लगाती",
  coolingRule: "कुछ करने से पहले मैं कितने मिनट रुकना चाहता/चाहती हूँ",
  notSet: "तय नहीं",
  save: "सहेजें",
  saved: "इसी फ़ोन में सहेजा गया",
  saveFailed: "इस फ़ोन ने सहेजने की अनुमति नहीं दी।",

  settingsEyebrow: "सेटिंग्स",
  settingsTitle: "Ruko को अपने हिसाब से बनाएँ।",
  languageLabel: "भाषा",
  languageDraft: "हिंदी और कन्नड़ पाठ अभी मसौदा है, मूल भाषी की समीक्षा बाकी है।",
  largeText: "बड़े अक्षर",
  styleLabel: "Ruko कितना बोले?",
  styleQuiet: "शांत: सिर्फ़ ज़रूरी बातें",
  styleBalanced: "संतुलित: कुछ खास दिखे तो एक छोटा नोट",
  styleNote: "जो ज़रूरी है वह Ruko फिर भी बताता है। यह सिर्फ़ वैकल्पिक अतिरिक्त बातें कम करता है।",
  exportTitle: "मेरा गुमनाम सारांश डाउनलोड करें",
  exportBody: "सिर्फ़ गिनतियाँ: कोई मैसेज, रकम या नोट नहीं। पायलट के लिए, अगर आप साझा करना चाहें।",
  exportButton: "सारांश डाउनलोड करें",
  exportDone: "सारांश डाउनलोड हो गया।",
  demoMenu: "डेमो टूल",
  demoBroker: "काल्पनिक ब्रोकर डेमो",
  versionLine: "Ruko प्रोटोटाइप",

  onboardEyebrow: "स्वागत है",
  onboardLanguageTitle: "अपनी भाषा चुनें",
  onboardLanguageBody: "आप इसे कभी भी सेटिंग्स में बदल सकते हैं।",
  onboardRulesTitle: "चाहें तो अपने नियम बनाएँ।",
  onboardRulesBody:
    "शांत मन से लिखे नियम ही Ruko बाद में आपको दिखाता है। सब वैकल्पिक, और इसी फ़ोन में रहते हैं।",
  onboardStyleTitle: "Ruko कितना बोले?",
  onboardNext: "आगे",
  onboardStart: "Ruko इस्तेमाल करना शुरू करें",
  onboardSkip: "छोड़ें, सुरक्षित डिफ़ॉल्ट लें",
  onboardSafeDefaults:
    "सुरक्षित डिफ़ॉल्ट: आपने कोई नियम नहीं रखा है, और Ruko अपनी बनाई किसी संख्या से तुलना नहीं करता।",

  offlineNote:
    "आप ऑफ़लाइन हैं। आपके नियम, डायरी और चेकलिस्ट फिर भी चलते हैं। मैसेज जाँचने के लिए कनेक्शन चाहिए।",

  errorEyebrow: "कुछ गड़बड़ हुई",
  errors: {
    backend_unavailable: "अभी Ruko तक पहुँचा नहीं जा सकता। अपना कनेक्शन देखें और फिर कोशिश करें।",
    timeout: "इसमें सामान्य से ज़्यादा समय लग रहा है। कृपया फिर कोशिश करें।",
    invalid_response: "Ruko को ऐसा जवाब मिला जो वह पढ़ नहीं सका। कृपया फिर कोशिश करें।",
    unsupported_input: "Ruko इस तरह की फ़ाइल नहीं पढ़ सकता। इसकी जगह पाठ चिपकाकर देखें।",
    reading_unavailable:
      "अभी Ruko स्क्रीनशॉट या आवाज़ नहीं पढ़ सकता। इसकी जगह पाठ चिपकाकर देखें।",
    too_many_requests: "थोड़े समय में बहुत ज़्यादा जाँच हो गईं। एक मिनट रुककर फिर कोशिश करें।",
    invalid_request: "Ruko वह इनपुट इस्तेमाल नहीं कर सका। मैसेज फिर से चिपकाकर देखें।",
    server_error: "Ruko की तरफ़ कुछ गड़बड़ हुई। कृपया फिर कोशिश करें।",
  },
  tryAgain: "फिर कोशिश करें",
  startOver: "फिर से शुरू करें",
};
