// Hindi chrome text. DRAFT: every string here awaits native-speaker review (see status.ts).

import type { Copy } from "./en";

export const hi: Copy = {
  privateByDesign: "डिज़ाइन से ही निजी",
  homeEyebrow: "आपका फ़ैसले का स्थान",
  homeTitle: "कुछ करने से पहले, एक पल रुकिए।",
  homeBody:
    "पैसों से जुड़े फ़ैसले को शांति से सोचने की जगह। Ruko आपको रुकने में मदद करता है; फ़ैसला आपका ही रहता है।",
  shareSomething: "कुछ साझा करें",
  shareHint: "सिर्फ़ वही लाएँ जो आप साझा करना चाहें।",
  thinkDecision: "किसी फ़ैसले पर सोचें",
  myRules: "मेरे नियम",
  myRulesHint: "आपकी प्रतिबद्धताएँ, आपकी शर्तों पर",
  journal: "डायरी",
  journalHint: "पिछला फ़ैसला देखें",
  homeFooter: "सिर्फ़ वही जाँचा जाता है जो आप साझा करें · ब्रोकर, OTP या SMS तक कोई पहुँच नहीं",
  workOutNumber: "कोई संख्या निकालें",
  workOutNumberHint: "SIP, लक्ष्य, कीमत में गिरावट",
  alreadyPaid: "मैं पैसे दे चुका/चुकी हूँ",
  alreadyPaidHint: "क्रम से, कदम-दर-कदम मदद",
  myPatterns: "मेरे पैटर्न",
  myPatternsHint: "आपकी अपनी डायरी क्या दिखाती है",
  settings: "सेटिंग्स",
  settingsHint: "भाषा, अक्षरों का आकार, Ruko कितना बोले",

  composeEyebrow: "Ruko के साथ साझा",
  composeDecisionEyebrow: "किसी फ़ैसले पर सोचें",
  composeLabel: "जो मैसेज मिला उसे यहाँ चिपकाएँ",
  composeDecisionLabel: "आप क्या करने की सोच रहे हैं?",
  composePlaceholder: "मैसेज यहाँ चिपकाएँ या लिखें",
  composeAddScreenshot: "इसकी जगह स्क्रीनशॉट जोड़ें",
  composeRemoveScreenshot: "स्क्रीनशॉट हटाएँ",
  composeScreenshotChosen: "स्क्रीनशॉट जोड़ा गया",
  composeSubmit: "इसे देखें",
  composeEmpty: "पहले कोई मैसेज चिपकाएँ या स्क्रीनशॉट जोड़ें।",
  composeFooter:
    "Ruko सिर्फ़ वही देखता है जो आप साझा करें। OTP, PIN या पासवर्ड कभी न चिपकाएँ।",
  messageYouReceived: "आपको मिला एक मैसेज",
  back: "वापस",

  voiceStart: "बोलकर बताएँ",
  voiceStop: "रोकें और भेजें",
  voiceCancel: "रद्द करें",
  voiceRecording: (seconds: number, max: number) => `रिकॉर्डिंग… ${max} में से ${seconds} सेकंड`,
  voiceSending: "आपका वॉइस नोट पढ़ा जा रहा है…",
  voiceTextAlways: "आप हमेशा लिखकर या चिपकाकर भी बता सकते हैं।",
  voiceProblems: {
    unsupported: "इस फ़ोन का ब्राउज़र आवाज़ रिकॉर्ड नहीं कर सकता। लिखें या चिपकाएँ।",
    permission_denied:
      "माइक्रोफ़ोन की अनुमति नहीं मिली, इसलिए Ruko उसे इस्तेमाल नहीं कर सकता। आप ब्राउज़र सेटिंग्स में अनुमति दे सकते हैं, या लिखकर बता सकते हैं।",
    no_microphone: "कोई माइक्रोफ़ोन नहीं मिला। लिखें या चिपकाएँ।",
    too_large: "यह रिकॉर्डिंग भेजने के लिए बहुत बड़ी है। छोटी रिकॉर्डिंग आज़माएँ।",
    empty: "कुछ रिकॉर्ड नहीं हुआ। फिर कोशिश करें, या लिखकर बताएँ।",
    failed: "इस बार रिकॉर्डिंग नहीं हो पाई। फिर कोशिश करें, या लिखकर बताएँ।",
  },

  processingTitle: "आपने जो साझा किया उसे देख रहे हैं…",
  processingBody: "मैसेज और उसके संकेतों को समझ रहे हैं।",

  clarifyEyebrow: "एक छोटा सवाल",
  clarifyAmountPlaceholder: "रकम ₹ में",
  clarifyAmountInvalid: "पूरी रुपये की रकम लिखें, जैसे 20000।",
  clarifyNumberPlaceholder: "संख्या",
  clarifyNumberInvalid: "पूरी संख्या लिखें, जैसे 12।",
  clarifyNext: "आगे",
  clarifySkip: "बताना नहीं चाहता/चाहती",
  clarifyFooter: "Ruko सिर्फ़ वही पूछता है जो ज़रूरी है। आपके जवाब इसी फ़ैसले तक रहते हैं।",

  levelEyebrow: {
    L0: "कुछ खास नहीं दिखा",
    L1: "एक हल्का इशारा",
    L2: "कदम उठाने से पहले एक पल",
    L3: "सोच-समझकर रुकना",
  },
  whatISee: "मुझे क्या दिखता है",
  yourContext: "आपकी स्थिति",
  cannotTell: "सिर्फ़ मैसेज देखकर Ruko यह नहीं बता सकता कि कोई ऑफ़र असली है या नहीं।",
  learnWhy: "जानें यह क्यों मायने रखता है",
  thinkThrough: "इस पर सोचें",
  learn: "जानें",
  continue: "आगे बढ़ें",
  pauseFooterL1: "Ruko आपके लिए फ़ैसला नहीं करता।",
  pauseFooter: "आगे क्या होगा, यह आपके हाथ में रहता है।",

  timerTitle: "रुकने का एक पल",
  timerBody: (minutes: number) => `${minutes} मिनट अलग रखे गए हैं। काम आएँ तो इस्तेमाल करें।`,
  timerRemaining: (time: string) => `${time} बाकी`,
  timerSkip: "इंतज़ार छोड़ें",
  timerDone: "इंतज़ार पूरा हुआ। फ़ैसला आपका है।",
  timerSkipped: "आपने इंतज़ार छोड़ दिया। यह आपका फ़ैसला है।",

  learnEyebrow: "यह क्यों मायने रखता है",
  lessonEyebrow: "एक छोटा पाठ",
  lessonReadTime: (seconds: number) => `पढ़ने में करीब ${seconds} सेकंड`,
  lessonTool: "कैलकुलेटर आज़माएँ",
  stepSee: "देखें",
  stepThink: "सोचें",
  stepDecide: "तय करें",
  stepsLabel: "इस फ़ैसले में आप कहाँ हैं",
  moneyThisDecision: "यह फ़ैसला",
  moneyOfSavings: "आपकी बचत का",
  moneyMonths: "महीनों के खर्च के बराबर",
  moneyAbout: "लगभग",
  moneyYourSavings: "आपकी बचत",
  moneyLeft: (amount: string, approx: boolean) => `${approx ? "लगभग " : ""}${amount} बचेंगे`,
  moneyInWords: "आपके आँकड़े शब्दों में",
  movesTitle: "अगर कीमत आपके ख़िलाफ़ जाए (गणित, अनुमान नहीं)",
  moveLine: (pct: string) => `${pct}% बदलाव`,
  movesNote: "बिंदुदार रेखा आपके लगाए पैसे की है। उससे आगे की पट्टी का मतलब उससे ज़्यादा नुकसान।",
  shortsNext: "आगे",
  shortsHint: "अगले कार्ड के लिए ऊपर स्वाइप करें",
  shortsEndTitle: "अब आप तय कर सकते हैं",
  shortsEndBody: "इस फ़ैसले के लिए इतना ही ज़रूरी था। चुनाव आपका है।",
  shortsLessonDone: "पाठ पूरा हुआ",
  calcMineLast: (amount: string) => `मेरा पिछला फ़ैसला: ${amount}`,
  calcMineGoal: (amount: string) => `मेरा लक्ष्य: ${amount}`,
  calcMinePlan: (amount: string) => `मेरी योजना: ${amount} तक`,
  calcYears: (years: number) => `${years} साल`,
  greetMorning: "सुप्रभात",
  greetAfternoon: "नमस्ते",
  greetEvening: "शुभ संध्या",
  snapshotTitle: "अब तक आपका Ruko",
  snapshotRules: "आपके अपने नियम",
  snapshotDecisions: "इस हफ़्ते के फ़ैसले",
  snapshotLessons: "पढ़े गए पाठ",
  lessonOwnGuidance: "यह Ruko की सामान्य सलाह है, किसी आधिकारिक स्रोत की नहीं।",
  learnTile: "सीखें",
  learnTileHint: "आसान भाषा में छोटे पाठ",
  learnHubIntro:
    "आसान भाषा में छोटे पाठ, सबके लिए। Ruko में कहीं भी रंगीन शब्द पर टैप करके उसका मतलब देखें।",
  learnProgress: (read: number, total: number) => `${total} में से ${read} पढ़े`,
  learnFeatured: "आपके लिए अगला",
  learnRead: "यह पाठ पढ़ें",
  learnReadAgain: "फिर से पढ़ें",
  learnAllRead: "आपने सारे पाठ पढ़ लिए हैं। फिर से पढ़ने के लिए कोई भी खोलें।",
  learnEmpty: "पाठ यहाँ तब दिखेंगे जब कोई व्यक्ति उन्हें जाँच लेगा।",
  learnWords: "ऐसे शब्द जो आप सुनेंगे",
  learnWordsHint: "छोटी व्याख्या के लिए शब्द पर टैप करें।",
  learnLoading: "पाठ लाए जा रहे हैं…",
  learnSeen: "पढ़ा",
  lessonNext: "आगे पढ़ें",
  lessonBackToLearn: "सीखें पर वापस",
  lessonBack: "वापस",
  termMore: "पूरी व्याख्या",
  termClose: "बंद करें",
  learnNextTitle: "जानने लायक",
  homeLearnTitle: "आपके लिए एक पाठ",
  asOf: (date: string) => `${date} तक की जानकारी`,
  unverified: "अभी किसी व्यक्ति ने जाँचा नहीं है",
  source: "स्रोत",

  listen: "सुनें",
  listenStop: "रोकें",
  listenLoading: "आवाज़ ला रहे हैं…",
  listenBrowserVoice: "अभी Ruko की आवाज़ उपलब्ध नहीं है, इसलिए आपके फ़ोन की अपनी आवाज़ इसे पढ़ रही है।",
  listenUnavailable: "इस फ़ोन पर अभी सुनना उपलब्ध नहीं है।",

  reflectEyebrow: "एक छोटा विचार",
  reflectTitle: "आप यह क्यों करना चाहते हैं?",
  reflectBody: "जो सबसे करीब लगे उसे चुनें। संक्षेप में भी चलेगा।",
  reflectChoices: [
    "किसी ने सुझाया",
    "कुछ छूट जाने का डर है",
    "मैं इस मौके को समझता/समझती हूँ",
    "मुझे जल्दी रिटर्न चाहिए",
    "कुछ और",
  ],
  reflectOwnWords: "या अपने शब्दों में लिखें",
  reflectPlaceholder: "एक विचार लिखें…",
  reflectSkip: "आप यह चरण छोड़ भी सकते हैं",
  reflectSkipButton: "छोड़ें",

  decideEyebrow: "आपका फ़ैसला",
  decideTitle: "आप क्या करेंगे?",
  decideBody: "जो भी चुनें, वह आपका फ़ैसला है।",
  actions: {
    went_ahead: "आगे बढ़ूँगा/बढ़ूँगी",
    delayed: "अभी रुकूँगा/रुकूँगी",
    changed_amount: "रकम बदलूँगा/बदलूँगी",
    dropped: "नहीं करूँगा/करूँगी",
    set_plan: "पहले योजना बनाऊँगा/बनाऊँगी",
  },
  actionPast: {
    went_ahead: "मैंने आगे बढ़ने का फ़ैसला किया।",
    delayed: "मैंने रुकने का फ़ैसला किया।",
    changed_amount: "मैंने रकम बदलने का फ़ैसला किया।",
    dropped: "मैंने इसे न करने का फ़ैसला किया।",
    set_plan: "मैंने पहले योजना बनाने का फ़ैसला किया।",
  },

  journalEyebrow: "आपकी डायरी",
  journalSavedTitle: "फ़ैसला दर्ज हो गया।",
  journalSavedBody: "आपके भविष्य के लिए एक नोट।",
  whatIConsidered: "मैंने क्या देखा",
  why: "क्यों",
  myDecision: "मेरा फ़ैसला",
  journalOutro: "आपके फ़ैसले आपके ही रहते हैं। जब आप सोचने के लिए एक पल चाहें, Ruko यहीं है।",
  done: "हो गया",
  dontKeep: "यह नोट न रखें",
  journalFooter: "डायरी वैकल्पिक है और सिर्फ़ आपकी है। यह इसी फ़ोन में रहती है।",
  journalEmpty: "अभी कोई फ़ैसला नहीं। जब आप किसी पर सोचेंगे, तो यहाँ एक छोटा नोट रखा जा सकता है।",
  aScreenshot: "एक स्क्रीनशॉट",
  aVoiceNote: "एक वॉइस नोट",
  notStated: "लिखा नहीं गया",
  feelingAsk: "वह ठहराव कैसा लगा? (वैकल्पिक)",
  feelingHelpful: "मददगार",
  feelingFine: "ठीक",
  feelingAnnoying: "परेशान करने वाला",
  feelingThanks: "धन्यवाद। इसी फ़ोन में दर्ज हो गया।",

  reportEyebrow: "मैसेज क्या दिखाता है",
  nothingFound: "बताने लायक कुछ नहीं",
  glossaryEyebrow: "आसान शब्दों में",
  recoveryEyebrow: "मदद पाना",
  recoveryUrgent: "यह अभी करें",
  recoveryEvidence: "ये सबूत सँभालकर रखें",
  recoveryDraft: "शिकायत का मसौदा (इसे आप खुद भेजें)",
  recoveryTicked: (done: number, total: number) => `${total} में से ${done} जुटाए`,
  copy: "कॉपी करें",
  copied: "कॉपी हो गया",
  refusalEyebrow: "जो Ruko नहीं करता",
  calcEyebrow: "गणित",
  calcAssumptions: "मान्यताएँ",
  calcIllustration: "यह गणित का एक उदाहरण है, कोई अनुमान नहीं।",
  chartPutIn: "लगाया गया",
  chartAltSeries: "समय के साथ लगाई गई रकम और मूल्य का लाइन चार्ट, हर मान्यता की एक लाइन।",
  chartAltBars: "हर काल्पनिक गिरावट के नतीजे का बार चार्ट।",
  shareSomethingElse: "कुछ और साझा करें",
  home: "होम",
  recoveryOpen: "अभी मदद लें",

  recoverEyebrow: "अगर आप पैसे दे चुके हैं",
  recoverTitle: "एक-एक कदम करके चलते हैं।",
  recoverBody: "कुछ हाँ-ना वाले सवाल, ताकि कदम आपकी स्थिति से मेल खाएँ। यहाँ से कुछ भी किसी को नहीं भेजा जाता।",
  recoverPaid: "क्या आपके खाते से पैसे गए?",
  recoverMethod: "आपने भुगतान कैसे किया?",
  recoverInstalled: "क्या आपने उनका भेजा ऐप इंस्टॉल किया, या अपनी स्क्रीन साझा की?",
  recoverBroker: "क्या यह आपके अपने पंजीकृत ब्रोकर या डीमैट खाते से जुड़ा है?",
  recoverUnauthorised: "क्या आपके खाते में ऐसा ट्रेड हुआ जो आपने नहीं किया?",
  recoverCannotWithdraw: "क्या कोई प्लेटफ़ॉर्म आपको पैसे निकालने नहीं दे रहा?",
  yes: "हाँ",
  no: "नहीं",
  paymentMethods: {
    upi: "UPI",
    bank_transfer: "बैंक ट्रांसफ़र",
    card: "कार्ड",
    cash_or_other: "नकद या अन्य",
    none: "लागू नहीं",
  },
  recoverSubmit: "मुझे बताएँ क्या करना है",
  recoverFooter: "Ruko खाता नंबर, OTP या PIN नहीं माँगता, और आपकी ओर से कुछ भेजता नहीं।",

  mirrorEyebrow: "मेरे पैटर्न",
  mirrorTitle: "आपकी अपनी डायरी क्या दिखाती है।",
  mirrorBody:
    "आपकी डायरी से निकाला गया। इस दृश्य के लिए सिर्फ़ प्रविष्टियाँ भेजी जाती हैं, नोट नहीं, और कुछ भी रखा नहीं जाता।",
  mirrorEmpty: "पहले अपनी डायरी में कुछ फ़ैसले जोड़ें। फिर आपके पैटर्न यहाँ दिखेंगे।",
  mirrorOffline: "पैटर्न देखने के लिए कनेक्शन चाहिए। आपकी डायरी बिना कनेक्शन के भी चलती है।",
  mirrorOutro: "ये आपकी अपनी संख्याएँ हैं, कोई स्कोर नहीं। कम ठहराव का मतलब अपने-आप बेहतर नहीं होता।",
  mirrorMetrics: {
    total_decisions: "डायरी में फ़ैसले",
    unsolicited_share_pct: "ग्रुप टिप या इन्फ़्लुएंसर से शुरू हुए",
    plans_set_pct: "लिखित योजना वाले फ़ैसले",
    pauses: "दिखाए गए ठहराव",
    pause_completion_pct: "जो ठहराव आपने पूरे पढ़े",
    comprehension_pct: "जहाँ आप बता सके कि ठहराव क्यों आया",
    reconsideration_pct: "ठहराव के बाद जहाँ आपने बदला, रुके या योजना बनाई",
    overrides_with_reason: "ठहराव के बावजूद आगे बढ़े, कारण के साथ",
    overrides_without_reason: "ठहराव के बावजूद आगे बढ़े, बिना कारण",
  },
  mirrorWeekly: "हर फ़ैसले पर ठहराव, हफ़्ते-दर-हफ़्ते",
  mirrorWeek: (date: string) => `${date} वाला हफ़्ता`,
  mirrorNotEnough: "अभी काफ़ी नहीं",

  rulesEyebrow: "मेरे नियम",
  rulesTitle: "आपकी प्रतिबद्धताएँ, आपकी शर्तों पर।",
  rulesBody: "वैकल्पिक। सिर्फ़ इसी फ़ोन में सहेजे जाते हैं और हर जाँच के साथ भेजे जाते हैं ताकि Ruko तुलना कर सके।",
  expenses: "मासिक खर्च",
  savings: "बचत जो जल्दी मिल सके",
  maxShare: "एक फ़ैसले में अपनी बचत का ज़्यादा से ज़्यादा इतना %",
  maxAmount: "एक फ़ैसले में ज़्यादा से ज़्यादा इतने रुपये",
  emergencyBuffer: "खर्च के कितने महीने मैं अछूते रखना चाहता/चाहती हूँ",
  protectedGoal: "किसी लक्ष्य के लिए अलग रखा पैसा जिसे मैं नहीं छुऊँगा/छुऊँगी (₹)",
  noBorrowed: "मैं उधार के पैसे नहीं लगाता/लगाती",
  coolingRule: "कुछ करने से पहले मैं कितने मिनट रुकना चाहता/चाहती हूँ",
  notSet: "तय नहीं",
  save: "सहेजें",
  saved: "इसी फ़ोन में सहेजा गया",
  saveFailed: "इस फ़ोन ने सहेजने की अनुमति नहीं दी।",

  settingsEyebrow: "सेटिंग्स",
  settingsTitle: "Ruko को अपने हिसाब से बनाएँ।",
  languageLabel: "भाषा",
  languageDraft: "हिंदी और कन्नड़ पाठ अभी मसौदा है, मूल भाषी की समीक्षा बाकी है।",
  largeText: "बड़े अक्षर",
  styleLabel: "Ruko कितना बोले?",
  styleQuiet: "शांत: सिर्फ़ ज़रूरी बातें",
  styleBalanced: "संतुलित: कुछ खास दिखे तो एक छोटा नोट",
  styleNote: "जो ज़रूरी है वह Ruko फिर भी बताता है। यह सिर्फ़ वैकल्पिक अतिरिक्त बातें कम करता है।",
  exportTitle: "मेरा गुमनाम सारांश डाउनलोड करें",
  exportBody: "सिर्फ़ गिनतियाँ: कोई मैसेज, रकम या नोट नहीं। पायलट के लिए, अगर आप साझा करना चाहें।",
  exportButton: "सारांश डाउनलोड करें",
  exportDone: "सारांश डाउनलोड हो गया।",
  demoMenu: "डेमो टूल",
  demoBroker: "काल्पनिक ब्रोकर डेमो",
  versionLine: "Ruko प्रोटोटाइप",

  onboardEyebrow: "स्वागत है",
  onboardLanguageTitle: "अपनी भाषा चुनें",
  onboardLanguageBody: "आप इसे कभी भी सेटिंग्स में बदल सकते हैं।",
  onboardRulesTitle: "चाहें तो अपने नियम बनाएँ।",
  onboardRulesBody:
    "शांत मन से लिखे नियम ही Ruko बाद में आपको दिखाता है। सब वैकल्पिक, और इसी फ़ोन में रहते हैं।",
  onboardStyleTitle: "Ruko कितना बोले?",
  onboardNext: "आगे",
  onboardStart: "Ruko इस्तेमाल करना शुरू करें",
  onboardSkip: "छोड़ें, सुरक्षित डिफ़ॉल्ट लें",
  onboardSafeDefaults:
    "सुरक्षित डिफ़ॉल्ट: आपने कोई नियम नहीं रखा है, और Ruko अपनी बनाई किसी संख्या से तुलना नहीं करता।",


  // --- Adaptive questions, refine, quotes, plans, calculator, home (A to F). DRAFT. ---
  clarifyContinue: "आगे बढ़ें",
  clarifyChooseOne: "एक चुनें।",
  clarifyAnswerAfterSkip: "फिर भी बताऊँगा/बताऊँगी",
  lastTime: "पिछली बार",
  aboutYouTitle: "आपके बारे में थोड़ा (वैकल्पिक)",
  aboutYouNote: "एक बार पूछा जाता है और इसी फ़ोन में रहता है। इससे Ruko को सिर्फ़ तुलना करने में मदद मिलती है।",
  experienceQuestion: "इस तरह का फ़ैसला आपके लिए कितना जाना-पहचाना है?",
  experienceOptions: {
    none: "मेरे लिए नया है",
    some: "कुछ बार किया है",
    regular: "मैं यह नियमित करता/करती हूँ",
  },
  recentLossQuestion: "क्या हाल में आपको नुकसान हुआ है?",
  recentLossOptions: { yes: "हाँ, हाल में", no: "नहीं" },
  tradesQuestion: "इस हफ़्ते आपने कितने ट्रेड किए?",
  tradesOptions: { "0": "कोई नहीं", "1_5": "1 से 5", "6_20": "6 से 20", gt_20: "20 से ज़्यादा" },

  refineTitle: "इसे अपने पैसों के हिसाब से देखें",
  refineBody: "अपनी संख्याएँ जोड़ें, फिर Ruko दिखाएगा कि इसका आपके लिए क्या मतलब है।",
  refineButton: "मेरे लिए इसका मतलब दिखाएँ",

  yourMessageTitle: "आपका मैसेज, और Ruko ने क्या देखा",
  fromYourMessage: "आपके मैसेज से",
  showMessage: "मेरा मैसेज दिखाएँ",
  hideMessage: "मेरा मैसेज छिपाएँ",

  reflectByReason: {
    UNSOLICITED_SOURCE: "यह किसी अनजान ने भेजा है",
    URGENCY_PRESSURE: "आख़िरी तारीख़ मुझ पर दबाव डाल रही है",
    GUARANTEED_RETURN_CLAIM: "वादा किया गया रिटर्न लुभावना लग रहा है",
    PROFIT_SCREENSHOT_SOCIAL_PROOF: "दूसरे लोग कमाते दिख रहे हैं",
    AUTHORITY_CLAIM: "वे ऐसे बोल रहे हैं जैसे सबसे ज़्यादा जानते हों",
    POST_LOSS_REENTRY_DECLARED: "मैं पिछला नुकसान वापस पाना चाहता/चाहती हूँ",
    LATE_NIGHT_DECISION: "रात हो गई है और मैं इसे अभी निपटाना चाहता हूँ",
    HIGH_FREQUENCY_DECLARED: "मुझे सक्रिय ट्रेडिंग पसंद है",
    FIRST_TIME_PRODUCT: "मुझे कुछ नया आज़माने की उत्सुकता है",
  } as Record<string, string>,
  reflectFomo: "कुछ छूट जाने का डर है",
  reflectTrusted: "जिस पर मैं भरोसा करता/करती हूँ उसने सुझाया",
  reflectUnderstand: "मैं इसे समझता/समझती हूँ और सोच-विचार कर चुका/चुकी हूँ",
  reflectOther: "कुछ और",
  decideNow: "फ़ैसला करें",
  reflectOptional: "पहले कारण जोड़ें (वैकल्पिक)",
  paceNote: "आप आम तौर पर सोचने वाला चरण छोड़ देते हैं, इसलिए Ruko उसे छोड़ रहा है। आप चाहें तो कारण जोड़ सकते हैं।",
  changeAmountTitle: "इसकी जगह कितनी रकम जाँचना चाहेंगे?",
  changeAmountButton: "यह रकम जाँचें",
  amountPlaceholder: "रकम ₹ में",
  planAddedNote: "योजना जोड़ी गई। Ruko ने उसके साथ फिर से जाँचा।",

  planEyebrow: "आपकी योजना",
  planTitle: "अपनी योजना अपने शब्दों में लिखें।",
  planBody:
    "शब्द इसी फ़ोन में रहते हैं। Ruko सिर्फ़ यह जानता है कि आपने कौन-से हिस्से लिखे, ताकि वह देख सके कि योजना पूरी है या नहीं।",
  planReason: "मैं यह क्यों कर रहा/रही हूँ?",
  planHorizon: "मैं कितने समय तक रुकना चाहता/चाहती हूँ?",
  planHorizonOptions: {
    days: "कुछ दिन",
    weeks: "कुछ हफ़्ते",
    months: "कुछ महीने",
    years: "सालों तक",
    unsure: "अभी पक्का नहीं",
  },
  planReconsider: "किस बात पर मैं दोबारा सोचूँगा/सोचूँगी, या बाहर निकल जाऊँगा/जाऊँगी?",
  planRangeTitle: "इस योजना की रकम का दायरा (वैकल्पिक)",
  planFrom: "से ₹",
  planTo: "तक ₹",
  planSave: "इसे इस तरह के फ़ैसले की योजना के रूप में रखें",
  planSubmit: "यह योजना इस्तेमाल करें",
  planEmpty: "योजना का कम से कम एक हिस्सा लिखें: क्यों, कितने समय के लिए, या किस बात पर आप दोबारा सोचेंगे।",
  planRangeInvalid: "दोनों रकम पूरे रुपये में लिखें, और पहली रकम दूसरी से ज़्यादा न हो।",
  plansTitle: "मेरी योजनाएँ",
  plansEmpty: "अभी कोई योजना नहीं। कोई फ़ैसला आने पर आप एक लिख सकते हैं।",
  planRemove: "हटाएँ",
  planRange: (min: string, max: string) => `${min} से ${max}`,

  calcToolTitle: "अपनी संख्याएँ आज़माएँ",
  calcToolBody:
    "कोई भी संख्या बदलें और नतीजा बदल जाएगा। यह आपकी मान्यताओं पर आधारित गणित है, कोई अनुमान नहीं।",
  calcTools: {
    sip: "एक SIP",
    goal: "एक लक्ष्य",
    inflation: "महँगाई",
    consequence: "कीमत में गिरावट",
    costs: "ट्रेडिंग का खर्च",
  },
  calcFields: {
    monthly_inr: "मासिक रकम (₹)",
    months: "महीनों की संख्या",
    goal_inr: "लक्ष्य की रकम (₹)",
    already_saved_inr: "पहले से जमा (₹, वैकल्पिक)",
    amount_inr: "रकम (₹)",
    years: "सालों की संख्या",
    leverage: "लेवरेज, कितने गुना (1 यानी कोई नहीं)",
    trade_value_inr: "एक ट्रेड का मूल्य (₹)",
    trades_per_month: "एक महीने में ट्रेड",
  },
  calcRates: "आज़माने के लिए सालाना दरें (%)",
  calcDrops: "आज़माने के लिए गिरावट (%)",
  calcAddRate: "जोड़ें",
  calcRatePlaceholder: "जैसे 8",
  calcRateNote: "आपकी अपनी दरें Ruko की नामित उदाहरण दरों के साथ दिखती हैं।",
  calcRemove: (value: string) => `${value} हटाएँ`,
  calcUpdating: "अपडेट हो रहा है…",
  calcFillIn: "नतीजा देखने के लिए ऊपर की संख्याएँ भरें।",
  calcAdjust: "ये संख्याएँ बदलें",

  waitDueTitle: "आपका इंतज़ार पूरा हुआ",
  waitPendingTitle: "आपने रुकने का फ़ैसला किया था",
  waitDueBody: "क्या अब भी इस पर सोच रहे हैं? दोनों तरह से फ़ैसला आपका है।",
  waitPendingBody: "इंतज़ार पूरा होने पर Ruko फिर पूछेगा।",
  waitLookAgain: "इसे फिर से देखें",
  waitLetGo: "मैंने इसे छोड़ दिया",
  planFollowTitle: "क्या आपने अपनी योजना का पालन किया?",
  planFollowBody: (date: string) => `आपने ${date} को योजना लिखी थी।`,
  planYes: "हाँ",
  planNo: "इस बार नहीं",
  planNotYet: "अभी नहीं",
  homeBack: "फिर से स्वागत है।",
  notNow: "अभी नहीं",
  moneyCheckText: "निवेश करने की सोच रहा हूँ",
  homeRulesNudgeTitle: "अपना एक नियम बनाएँ",
  homeRulesNudgeBody: "जब आप शांति से तय करते हैं, तो Ruko बाद में उसे आपको याद दिला सकता है।",
  homeRulesNudgeButton: "नियम बनाएँ",
  homePatternsNudgeTitle: "देखें आपकी डायरी क्या दिखाती है",
  homePatternsNudgeBody: "आपके कुछ फ़ैसले दर्ज हैं।",
  bridgeMoney: "दिखाएँ कि कोई रकम मेरे पैसों के लिए क्या मायने रखेगी",
  bridgeMoneyNote:
    "Ruko यह नहीं बता सकता कि खरीदना है या नहीं, पर वह दिखा सकता है कि कोई रकम आपकी बचत और आपके नियमों के लिए क्या मायने रखती है।",
  bridgeFall: "देखें कि गिरावट रुपयों में क्या होगी",
  bridgeFallNote: "आगे क्या होगा यह कोई नहीं बता सकता, पर गिरावट का हिसाब सिर्फ़ गणित है।",
  glossaryMore: "और शब्द जो Ruko समझा सकता है",
  profileExperience: "हर एक से मैं कितना परिचित हूँ (वैकल्पिक)",
  ageBandLabel: "मेरी उम्र (वैकल्पिक)",
  ageBands: {
    lt_30: "30 से कम",
    "30_40": "30 से 40",
    "40_50": "40 से 50",
    "50_60": "50 से 60",
    gt_60: "60 से ज़्यादा",
  },
  productNames: {
    cash_equity: "कंपनी के शेयर",
    derivative: "फ़्यूचर्स या ऑप्शंस (F&O)",
    ipo: "एक IPO",
    mutual_fund: "एक म्यूचुअल फ़ंड",
    crypto: "क्रिप्टो",
  },

  offlineNote:
    "आप ऑफ़लाइन हैं। आपके नियम, डायरी और चेकलिस्ट फिर भी चलते हैं। मैसेज जाँचने के लिए कनेक्शन चाहिए।",

  errorEyebrow: "कुछ गड़बड़ हुई",
  errors: {
    backend_unavailable: "अभी Ruko तक पहुँचा नहीं जा सकता। अपना कनेक्शन देखें और फिर कोशिश करें।",
    timeout: "इसमें सामान्य से ज़्यादा समय लग रहा है। कृपया फिर कोशिश करें।",
    invalid_response: "Ruko को ऐसा जवाब मिला जो वह पढ़ नहीं सका। कृपया फिर कोशिश करें।",
    unsupported_input: "Ruko इस तरह की फ़ाइल नहीं पढ़ सकता। इसकी जगह पाठ चिपकाकर देखें।",
    reading_unavailable:
      "अभी Ruko स्क्रीनशॉट या आवाज़ नहीं पढ़ सकता। इसकी जगह पाठ चिपकाकर देखें।",
    too_many_requests: "थोड़े समय में बहुत ज़्यादा जाँच हो गईं। एक मिनट रुककर फिर कोशिश करें।",
    invalid_request: "Ruko वह इनपुट इस्तेमाल नहीं कर सका। मैसेज फिर से चिपकाकर देखें।",
    server_error: "Ruko की तरफ़ कुछ गड़बड़ हुई। कृपया फिर कोशिश करें।",
  },
  tryAgain: "फिर कोशिश करें",
  startOver: "फिर से शुरू करें",
};
