// Kannada chrome text. DRAFT: every string here awaits native-speaker review (see status.ts).

import type { Copy } from "./en";

export const kn: Copy = {
  privateByDesign: "ವಿನ್ಯಾಸದಿಂದಲೇ ಖಾಸಗಿ",
  homeEyebrow: "ನಿಮ್ಮ ನಿರ್ಧಾರದ ಸ್ಥಳ",
  homeTitle: "ಕ್ರಮ ಕೈಗೊಳ್ಳುವ ಮೊದಲು, ಒಂದು ಕ್ಷಣ ನಿಲ್ಲಿ.",
  homeBody:
    "ಹಣಕಾಸಿನ ನಿರ್ಧಾರವನ್ನು ಶಾಂತವಾಗಿ ಯೋಚಿಸಲು ಒಂದು ಸ್ಥಳ. Ruko ನಿಮಗೆ ನಿಲ್ಲಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ; ಆಯ್ಕೆ ನಿಮ್ಮದೇ ಆಗಿರುತ್ತದೆ.",
  shareSomething: "ಏನಾದರೂ ಹಂಚಿಕೊಳ್ಳಿ",
  shareHint: "ನೀವು ಹಂಚಿಕೊಳ್ಳಲು ಬಯಸಿದ್ದನ್ನು ಮಾತ್ರ ತನ್ನಿ.",
  thinkDecision: "ಒಂದು ನಿರ್ಧಾರದ ಬಗ್ಗೆ ಯೋಚಿಸಿ",
  myRules: "ನನ್ನ ನಿಯಮಗಳು",
  myRulesHint: "ನಿಮ್ಮ ಬದ್ಧತೆಗಳು, ನಿಮ್ಮ ಷರತ್ತುಗಳಲ್ಲಿ",
  journal: "ದಿನಚರಿ",
  journalHint: "ಹಿಂದಿನ ನಿರ್ಧಾರವನ್ನು ನೋಡಿ",
  homeFooter: "ನೀವು ಹಂಚಿಕೊಂಡದ್ದನ್ನು ಮಾತ್ರ ಪರಿಶೀಲಿಸಲಾಗುತ್ತದೆ · ಬ್ರೋಕರ್, OTP ಅಥವಾ SMS ಪ್ರವೇಶ ಇಲ್ಲ",
  workOutNumber: "ಒಂದು ಸಂಖ್ಯೆ ಲೆಕ್ಕ ಹಾಕಿ",
  workOutNumberHint: "SIP, ಗುರಿ, ಮೌಲ್ಯದಲ್ಲಿ ಇಳಿಕೆ",
  alreadyPaid: "ನಾನು ಈಗಾಗಲೇ ಹಣ ಪಾವತಿಸಿದ್ದೇನೆ",
  alreadyPaidHint: "ಕ್ರಮವಾಗಿ, ಹಂತ ಹಂತವಾಗಿ ಸಹಾಯ",
  myPatterns: "ನನ್ನ ಮಾದರಿಗಳು",
  myPatternsHint: "ನಿಮ್ಮ ದಿನಚರಿ ಏನು ತೋರಿಸುತ್ತದೆ",
  settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
  settingsHint: "ಭಾಷೆ, ಅಕ್ಷರದ ಗಾತ್ರ, Ruko ಎಷ್ಟು ಮಾತನಾಡಬೇಕು",

  composeEyebrow: "Ruko ಜೊತೆ ಹಂಚಿಕೊಂಡದ್ದು",
  composeDecisionEyebrow: "ಒಂದು ನಿರ್ಧಾರದ ಬಗ್ಗೆ ಯೋಚಿಸಿ",
  composeLabel: "ನಿಮಗೆ ಬಂದ ಸಂದೇಶವನ್ನು ಇಲ್ಲಿ ಅಂಟಿಸಿ",
  composeDecisionLabel: "ನೀವು ಏನು ಮಾಡಲು ಯೋಚಿಸುತ್ತಿದ್ದೀರಿ?",
  composePlaceholder: "ಸಂದೇಶವನ್ನು ಇಲ್ಲಿ ಅಂಟಿಸಿ ಅಥವಾ ಬರೆಯಿರಿ",
  composeAddScreenshot: "ಬದಲಿಗೆ ಸ್ಕ್ರೀನ್‌ಶಾಟ್ ಸೇರಿಸಿ",
  composeRemoveScreenshot: "ಸ್ಕ್ರೀನ್‌ಶಾಟ್ ತೆಗೆಯಿರಿ",
  composeScreenshotChosen: "ಸ್ಕ್ರೀನ್‌ಶಾಟ್ ಸೇರಿಸಲಾಗಿದೆ",
  composeSubmit: "ಇದನ್ನು ನೋಡಿ",
  composeEmpty: "ಮೊದಲು ಒಂದು ಸಂದೇಶವನ್ನು ಅಂಟಿಸಿ ಅಥವಾ ಸ್ಕ್ರೀನ್‌ಶಾಟ್ ಸೇರಿಸಿ.",
  composeFooter:
    "ನೀವು ಹಂಚಿಕೊಂಡದ್ದನ್ನು ಮಾತ್ರ Ruko ನೋಡುತ್ತದೆ. OTP, PIN ಅಥವಾ ಪಾಸ್‌ವರ್ಡ್ ಎಂದಿಗೂ ಅಂಟಿಸಬೇಡಿ.",
  messageYouReceived: "ನಿಮಗೆ ಬಂದ ಒಂದು ಸಂದೇಶ",
  back: "ಹಿಂದೆ",

  voiceStart: "ಬದಲಿಗೆ ಮಾತನಾಡಿ",
  voiceStop: "ನಿಲ್ಲಿಸಿ ಮತ್ತು ಕಳುಹಿಸಿ",
  voiceCancel: "ರದ್ದುಮಾಡಿ",
  voiceRecording: (seconds: number, max: number) => `ರೆಕಾರ್ಡಿಂಗ್… ${max} ರಲ್ಲಿ ${seconds} ಸೆಕೆಂಡ್`,
  voiceSending: "ನಿಮ್ಮ ಧ್ವನಿ ಸಂದೇಶವನ್ನು ಓದಲಾಗುತ್ತಿದೆ…",
  voiceTextAlways: "ನೀವು ಯಾವಾಗಲೂ ಬರೆದು ಅಥವಾ ಅಂಟಿಸಿ ಕೂಡ ಹೇಳಬಹುದು.",
  voiceProblems: {
    unsupported: "ಈ ಫೋನ್‌ನ ಬ್ರೌಸರ್ ಧ್ವನಿ ರೆಕಾರ್ಡ್ ಮಾಡಲು ಸಾಧ್ಯವಿಲ್ಲ. ಬರೆಯಿರಿ ಅಥವಾ ಅಂಟಿಸಿ.",
    permission_denied:
      "ಮೈಕ್ರೋಫೋನ್‌ಗೆ ಅನುಮತಿ ಸಿಗಲಿಲ್ಲ, ಆದ್ದರಿಂದ Ruko ಅದನ್ನು ಬಳಸಲಾಗದು. ನೀವು ಬ್ರೌಸರ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳಲ್ಲಿ ಅನುಮತಿ ನೀಡಬಹುದು, ಅಥವಾ ಬರೆಯಬಹುದು.",
    no_microphone: "ಯಾವುದೇ ಮೈಕ್ರೋಫೋನ್ ಸಿಗಲಿಲ್ಲ. ಬರೆಯಿರಿ ಅಥವಾ ಅಂಟಿಸಿ.",
    too_large: "ಈ ರೆಕಾರ್ಡಿಂಗ್ ಕಳುಹಿಸಲು ತುಂಬಾ ದೊಡ್ಡದು. ಚಿಕ್ಕದನ್ನು ಪ್ರಯತ್ನಿಸಿ.",
    empty: "ಏನೂ ರೆಕಾರ್ಡ್ ಆಗಲಿಲ್ಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ, ಅಥವಾ ಬರೆದು ಹೇಳಿ.",
    failed: "ಈ ಬಾರಿ ರೆಕಾರ್ಡಿಂಗ್ ಆಗಲಿಲ್ಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ, ಅಥವಾ ಬರೆದು ಹೇಳಿ.",
  },

  processingTitle: "ನೀವು ಹಂಚಿಕೊಂಡದ್ದನ್ನು ನೋಡಲಾಗುತ್ತಿದೆ…",
  processingBody: "ಸಂದೇಶ ಮತ್ತು ಅದರ ಸೂಚನೆಗಳನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲಾಗುತ್ತಿದೆ.",

  clarifyEyebrow: "ಒಂದು ಸಣ್ಣ ಪ್ರಶ್ನೆ",
  clarifyAmountPlaceholder: "ಮೊತ್ತ ₹ ನಲ್ಲಿ",
  clarifyAmountInvalid: "ಪೂರ್ಣ ರೂಪಾಯಿ ಮೊತ್ತ ಬರೆಯಿರಿ, ಉದಾ. 20000.",
  clarifyNumberPlaceholder: "ಸಂಖ್ಯೆ",
  clarifyNumberInvalid: "ಪೂರ್ಣ ಸಂಖ್ಯೆ ಬರೆಯಿರಿ, ಉದಾ. 12.",
  clarifyNext: "ಮುಂದೆ",
  clarifySkip: "ಹೇಳಲು ಇಷ್ಟವಿಲ್ಲ",
  clarifyFooter: "Ruko ಅಗತ್ಯವಿರುವುದನ್ನು ಮಾತ್ರ ಕೇಳುತ್ತದೆ. ನಿಮ್ಮ ಉತ್ತರಗಳು ಈ ನಿರ್ಧಾರದ ಜೊತೆಗೇ ಇರುತ್ತವೆ.",

  levelEyebrow: {
    L0: "ವಿಶೇಷವಾದದ್ದೇನೂ ಕಾಣಲಿಲ್ಲ",
    L1: "ಒಂದು ಸಣ್ಣ ಸೂಚನೆ",
    L2: "ಕ್ರಮಕ್ಕೆ ಮೊದಲು ಒಂದು ಕ್ಷಣ",
    L3: "ಯೋಚಿಸಿ ನಿಲ್ಲುವುದು",
  },
  whatISee: "ನನಗೆ ಏನು ಕಾಣುತ್ತದೆ",
  yourContext: "ನಿಮ್ಮ ಪರಿಸ್ಥಿತಿ",
  cannotTell: "ಸಂದೇಶವನ್ನು ನೋಡಿ ಮಾತ್ರ ಒಂದು ಆಫರ್ ನಿಜವೇ ಎಂದು Ruko ಹೇಳಲು ಸಾಧ್ಯವಿಲ್ಲ.",
  learnWhy: "ಇದು ಏಕೆ ಮುಖ್ಯ ಎಂದು ತಿಳಿಯಿರಿ",
  thinkThrough: "ಇದರ ಬಗ್ಗೆ ಯೋಚಿಸಿ",
  learn: "ತಿಳಿಯಿರಿ",
  continue: "ಮುಂದುವರಿಸಿ",
  pauseFooterL1: "Ruko ನಿಮ್ಮ ಪರವಾಗಿ ನಿರ್ಧರಿಸುವುದಿಲ್ಲ.",
  pauseFooter: "ಮುಂದೆ ಏನಾಗುತ್ತದೆ ಎಂಬುದು ನಿಮ್ಮ ಕೈಯಲ್ಲೇ ಇರುತ್ತದೆ.",

  timerTitle: "ಕಾಯಲು ಒಂದು ಕ್ಷಣ",
  timerBody: (minutes: number) => `${minutes} ನಿಮಿಷಗಳನ್ನು ಬದಿಗಿಡಲಾಗಿದೆ. ಸಹಾಯವಾದರೆ ಬಳಸಿ.`,
  timerRemaining: (time: string) => `${time} ಉಳಿದಿದೆ`,
  timerSkip: "ಕಾಯುವುದನ್ನು ಬಿಟ್ಟುಬಿಡಿ",
  timerDone: "ಕಾಯುವಿಕೆ ಮುಗಿಯಿತು. ಆಯ್ಕೆ ನಿಮ್ಮದು.",
  timerSkipped: "ನೀವು ಕಾಯುವುದನ್ನು ಬಿಟ್ಟಿರಿ. ಅದು ನಿಮ್ಮ ನಿರ್ಧಾರ.",

  learnEyebrow: "ಇದು ಏಕೆ ಮುಖ್ಯ",
  lessonEyebrow: "ಒಂದು ಚಿಕ್ಕ ಪಾಠ",
  lessonReadTime: (seconds: number) => `ಓದಲು ಸುಮಾರು ${seconds} ಸೆಕೆಂಡ್`,
  lessonTool: "ಕ್ಯಾಲ್ಕುಲೇಟರ್ ಪ್ರಯತ್ನಿಸಿ",
  stepSee: "ನೋಡಿ",
  stepThink: "ಯೋಚಿಸಿ",
  stepDecide: "ನಿರ್ಧರಿಸಿ",
  stepsLabel: "ಈ ನಿರ್ಧಾರದಲ್ಲಿ ನೀವು ಎಲ್ಲಿದ್ದೀರಿ",
  moneyThisDecision: "ಈ ನಿರ್ಧಾರ",
  moneyOfSavings: "ನಿಮ್ಮ ಉಳಿತಾಯದ",
  moneyMonths: "ತಿಂಗಳ ಖರ್ಚಿಗೆ ಸಮ",
  moneyAbout: "ಸುಮಾರು",
  moneyYourSavings: "ನಿಮ್ಮ ಉಳಿತಾಯ",
  moneyLeft: (amount: string, approx: boolean) => `${approx ? "ಸುಮಾರು " : ""}${amount} ಉಳಿಯುತ್ತದೆ`,
  moneyInWords: "ನಿಮ್ಮ ಅಂಕಿಗಳು ಪದಗಳಲ್ಲಿ",
  movesTitle: "ಬೆಲೆ ನಿಮ್ಮ ವಿರುದ್ಧ ಹೋದರೆ (ಲೆಕ್ಕ, ಮುನ್ಸೂಚನೆ ಅಲ್ಲ)",
  moveLine: (pct: string) => `${pct}% ಬದಲಾವಣೆ`,
  movesNote: "ಚುಕ್ಕೆ ಗೆರೆ ನೀವು ಹಾಕಿದ ಹಣ. ಅದನ್ನು ದಾಟಿದ ಪಟ್ಟಿ ಎಂದರೆ ಅದಕ್ಕಿಂತ ಹೆಚ್ಚು ನಷ್ಟ.",
  shortsNext: "ಮುಂದೆ",
  shortsHint: "ಮುಂದಿನ ಕಾರ್ಡ್‌ಗಾಗಿ ಮೇಲಕ್ಕೆ ಸ್ವೈಪ್ ಮಾಡಿ",
  shortsEndTitle: "ಈಗ ನೀವು ನಿರ್ಧರಿಸಬಹುದು",
  shortsEndBody: "ಈ ನಿರ್ಧಾರಕ್ಕೆ ಇಷ್ಟೇ ಬೇಕಿತ್ತು. ಆಯ್ಕೆ ನಿಮ್ಮದು.",
  shortsLessonDone: "ಪಾಠ ಮುಗಿಯಿತು",
  calcMineLast: (amount: string) => `ನನ್ನ ಹಿಂದಿನ ನಿರ್ಧಾರ: ${amount}`,
  calcMineGoal: (amount: string) => `ನನ್ನ ಗುರಿ: ${amount}`,
  calcMinePlan: (amount: string) => `ನನ್ನ ಯೋಜನೆ: ${amount} ವರೆಗೆ`,
  calcYears: (years: number) => `${years} ವರ್ಷ`,
  greetMorning: "ಶುಭೋದಯ",
  greetAfternoon: "ನಮಸ್ಕಾರ",
  greetEvening: "ಶುಭ ಸಂಜೆ",
  snapshotTitle: "ಇಲ್ಲಿಯವರೆಗೆ ನಿಮ್ಮ Ruko",
  snapshotRules: "ನಿಮ್ಮದೇ ನಿಯಮಗಳು",
  snapshotDecisions: "ಈ ವಾರದ ನಿರ್ಧಾರಗಳು",
  snapshotLessons: "ಓದಿದ ಪಾಠಗಳು",
  lessonOwnGuidance: "ಇದು Ruko ದ ಸಾಮಾನ್ಯ ಸಲಹೆ, ಅಧಿಕೃತ ಮೂಲದ್ದಲ್ಲ.",
  learnTile: "ಕಲಿಯಿರಿ",
  learnTileHint: "ಸರಳ ಭಾಷೆಯಲ್ಲಿ ಚಿಕ್ಕ ಪಾಠಗಳು",
  learnHubIntro:
    "ಸರಳ ಭಾಷೆಯಲ್ಲಿ ಚಿಕ್ಕ ಪಾಠಗಳು, ಎಲ್ಲರಿಗೂ. Ruko ದಲ್ಲಿ ಎಲ್ಲಿಯಾದರೂ ಬಣ್ಣದ ಪದದ ಮೇಲೆ ಟ್ಯಾಪ್ ಮಾಡಿ ಅದರ ಅರ್ಥ ನೋಡಿ.",
  learnProgress: (read: number, total: number) => `${total} ರಲ್ಲಿ ${read} ಓದಿದ್ದೀರಿ`,
  learnFeatured: "ನಿಮಗೆ ಮುಂದಿನದು",
  learnRead: "ಈ ಪಾಠ ಓದಿ",
  learnReadAgain: "ಮತ್ತೆ ಓದಿ",
  learnAllRead: "ನೀವು ಎಲ್ಲ ಪಾಠಗಳನ್ನು ಓದಿದ್ದೀರಿ. ಮತ್ತೆ ಓದಲು ಯಾವುದನ್ನಾದರೂ ತೆರೆಯಿರಿ.",
  learnEmpty: "ಒಬ್ಬ ವ್ಯಕ್ತಿ ಪರಿಶೀಲಿಸಿದ ನಂತರ ಪಾಠಗಳು ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತವೆ.",
  learnWords: "ನೀವು ಕೇಳುವ ಪದಗಳು",
  learnWordsHint: "ಚಿಕ್ಕ ವಿವರಣೆಗಾಗಿ ಪದದ ಮೇಲೆ ಟ್ಯಾಪ್ ಮಾಡಿ.",
  learnLoading: "ಪಾಠಗಳನ್ನು ತರಲಾಗುತ್ತಿದೆ…",
  learnSeen: "ಓದಿದ್ದು",
  lessonNext: "ಮುಂದೆ ಓದಿ",
  lessonBackToLearn: "ಕಲಿಯಿರಿಗೆ ಹಿಂತಿರುಗಿ",
  lessonBack: "ಹಿಂದೆ",
  termMore: "ಪೂರ್ಣ ವಿವರಣೆ",
  termClose: "ಮುಚ್ಚಿ",
  learnNextTitle: "ತಿಳಿಯಲು ಯೋಗ್ಯ",
  homeLearnTitle: "ನಿಮಗಾಗಿ ಒಂದು ಪಾಠ",
  asOf: (date: string) => `${date} ರ ಮಾಹಿತಿ`,
  unverified: "ಇನ್ನೂ ಯಾವ ವ್ಯಕ್ತಿಯೂ ಪರಿಶೀಲಿಸಿಲ್ಲ",
  source: "ಮೂಲ",

  listen: "ಆಲಿಸಿ",
  listenStop: "ನಿಲ್ಲಿಸಿ",
  listenLoading: "ಧ್ವನಿಯನ್ನು ತರಲಾಗುತ್ತಿದೆ…",
  listenBrowserVoice:
    "ಈಗ Ruko ದ ಧ್ವನಿ ಲಭ್ಯವಿಲ್ಲ, ಆದ್ದರಿಂದ ನಿಮ್ಮ ಫೋನ್‌ನ ಸ್ವಂತ ಧ್ವನಿ ಇದನ್ನು ಓದುತ್ತಿದೆ.",
  listenUnavailable: "ಈ ಫೋನ್‌ನಲ್ಲಿ ಈಗ ಆಲಿಸುವುದು ಲಭ್ಯವಿಲ್ಲ.",

  reflectEyebrow: "ಒಂದು ಸಣ್ಣ ಆಲೋಚನೆ",
  reflectTitle: "ನೀವು ಇದನ್ನು ಏಕೆ ಮಾಡಲು ಬಯಸುತ್ತೀರಿ?",
  reflectBody: "ಹತ್ತಿರವೆನಿಸುವುದನ್ನು ಆರಿಸಿ. ಸಂಕ್ಷಿಪ್ತವಾಗಿದ್ದರೂ ಸಾಕು.",
  reflectChoices: [
    "ಯಾರೋ ಶಿಫಾರಸು ಮಾಡಿದರು",
    "ಅವಕಾಶ ತಪ್ಪುವ ಭಯವಿದೆ",
    "ನಾನು ಈ ಅವಕಾಶವನ್ನು ಅರ್ಥಮಾಡಿಕೊಂಡಿದ್ದೇನೆ",
    "ನನಗೆ ಬೇಗ ಲಾಭ ಬೇಕು",
    "ಬೇರೆ ಏನೋ",
  ],
  reflectOwnWords: "ಅಥವಾ ನಿಮ್ಮ ಮಾತುಗಳಲ್ಲಿ ಹೇಳಿ",
  reflectPlaceholder: "ಒಂದು ಆಲೋಚನೆ ಬರೆಯಿರಿ…",
  reflectSkip: "ನೀವು ಈ ಹಂತವನ್ನು ಬಿಟ್ಟುಬಿಡಬಹುದು",
  reflectSkipButton: "ಬಿಟ್ಟುಬಿಡಿ",

  decideEyebrow: "ನಿಮ್ಮ ನಿರ್ಧಾರ",
  decideTitle: "ನೀವು ಏನು ಮಾಡುತ್ತೀರಿ?",
  decideBody: "ನೀವು ಏನೇ ಆರಿಸಿದರೂ ಅದು ನಿಮ್ಮ ನಿರ್ಧಾರ.",
  actions: {
    went_ahead: "ಮುಂದುವರಿಯುತ್ತೇನೆ",
    delayed: "ಸದ್ಯ ಕಾಯುತ್ತೇನೆ",
    changed_amount: "ಮೊತ್ತ ಬದಲಿಸುತ್ತೇನೆ",
    dropped: "ಮಾಡುವುದಿಲ್ಲ",
    set_plan: "ಮೊದಲು ಯೋಜನೆ ಮಾಡುತ್ತೇನೆ",
  },
  actionPast: {
    went_ahead: "ನಾನು ಮುಂದುವರಿಯಲು ನಿರ್ಧರಿಸಿದೆ.",
    delayed: "ನಾನು ಕಾಯಲು ನಿರ್ಧರಿಸಿದೆ.",
    changed_amount: "ನಾನು ಮೊತ್ತ ಬದಲಿಸಲು ನಿರ್ಧರಿಸಿದೆ.",
    dropped: "ನಾನು ಇದನ್ನು ಮಾಡದಿರಲು ನಿರ್ಧರಿಸಿದೆ.",
    set_plan: "ನಾನು ಮೊದಲು ಯೋಜನೆ ಮಾಡಲು ನಿರ್ಧರಿಸಿದೆ.",
  },

  journalEyebrow: "ನಿಮ್ಮ ದಿನಚರಿ",
  journalSavedTitle: "ನಿರ್ಧಾರ ದಾಖಲಾಯಿತು.",
  journalSavedBody: "ನಿಮ್ಮ ಭವಿಷ್ಯದ ನಿಮಗಾಗಿ ಒಂದು ಟಿಪ್ಪಣಿ.",
  whatIConsidered: "ನಾನು ಏನನ್ನು ಪರಿಗಣಿಸಿದೆ",
  why: "ಏಕೆ",
  myDecision: "ನನ್ನ ನಿರ್ಧಾರ",
  journalOutro: "ನಿಮ್ಮ ನಿರ್ಧಾರಗಳು ನಿಮ್ಮವೇ. ಯೋಚಿಸಲು ಒಂದು ಕ್ಷಣ ಬೇಕಾದಾಗ Ruko ಇಲ್ಲಿದೆ.",
  done: "ಆಯಿತು",
  dontKeep: "ಈ ಟಿಪ್ಪಣಿ ಇಡಬೇಡಿ",
  journalFooter: "ದಿನಚರಿ ಐಚ್ಛಿಕ ಮತ್ತು ನಿಮಗೆ ಮಾತ್ರ. ಇದು ಈ ಫೋನ್‌ನಲ್ಲೇ ಇರುತ್ತದೆ.",
  journalEmpty: "ಇನ್ನೂ ಯಾವ ನಿರ್ಧಾರವೂ ಇಲ್ಲ. ನೀವು ಒಂದರ ಬಗ್ಗೆ ಯೋಚಿಸಿದಾಗ, ಒಂದು ಚಿಕ್ಕ ಟಿಪ್ಪಣಿ ಇಲ್ಲಿ ಇಡಬಹುದು.",
  aScreenshot: "ಒಂದು ಸ್ಕ್ರೀನ್‌ಶಾಟ್",
  aVoiceNote: "ಒಂದು ಧ್ವನಿ ಸಂದೇಶ",
  notStated: "ಬರೆದಿಲ್ಲ",
  feelingAsk: "ಆ ವಿರಾಮ ಹೇಗಿತ್ತು? (ಐಚ್ಛಿಕ)",
  feelingHelpful: "ಸಹಾಯಕ",
  feelingFine: "ಸರಿ",
  feelingAnnoying: "ಕಿರಿಕಿರಿ",
  feelingThanks: "ಧನ್ಯವಾದ. ಈ ಫೋನ್‌ನಲ್ಲಿ ದಾಖಲಾಯಿತು.",

  reportEyebrow: "ಸಂದೇಶ ಏನು ತೋರಿಸುತ್ತದೆ",
  nothingFound: "ವರದಿ ಮಾಡಲು ಏನೂ ಇಲ್ಲ",
  glossaryEyebrow: "ಸರಳವಾಗಿ ವಿವರಣೆ",
  recoveryEyebrow: "ಸಹಾಯ ಪಡೆಯುವುದು",
  recoveryUrgent: "ಇದನ್ನು ಈಗಲೇ ಮಾಡಿ",
  recoveryEvidence: "ಈ ಸಾಕ್ಷ್ಯಗಳನ್ನು ಇಟ್ಟುಕೊಳ್ಳಿ",
  recoveryDraft: "ದೂರಿನ ಕರಡು (ನೀವೇ ಕಳುಹಿಸಿ)",
  recoveryTicked: (done: number, total: number) => `${total} ರಲ್ಲಿ ${done} ಸಂಗ್ರಹಿಸಲಾಗಿದೆ`,
  copy: "ನಕಲಿಸಿ",
  copied: "ನಕಲಿಸಲಾಗಿದೆ",
  refusalEyebrow: "Ruko ಮಾಡದ ಕೆಲಸ",
  calcEyebrow: "ಲೆಕ್ಕಾಚಾರ",
  calcAssumptions: "ಊಹೆಗಳು",
  calcIllustration: "ಇದು ಲೆಕ್ಕಾಚಾರದ ಒಂದು ಉದಾಹರಣೆ, ಮುನ್ಸೂಚನೆ ಅಲ್ಲ.",
  chartPutIn: "ಹಾಕಿದ್ದು",
  chartAltSeries: "ಸಮಯದೊಂದಿಗೆ ಹಾಕಿದ ಹಣ ಮತ್ತು ಮೌಲ್ಯದ ಲೈನ್ ಚಾರ್ಟ್, ಪ್ರತಿ ಊಹೆಗೆ ಒಂದು ಲೈನ್.",
  chartAltBars: "ಪ್ರತಿ ಕಾಲ್ಪನಿಕ ಇಳಿಕೆಯ ಫಲಿತಾಂಶದ ಬಾರ್ ಚಾರ್ಟ್.",
  shareSomethingElse: "ಬೇರೆ ಏನಾದರೂ ಹಂಚಿಕೊಳ್ಳಿ",
  home: "ಮುಖಪುಟ",
  recoveryOpen: "ಈಗಲೇ ಸಹಾಯ ಪಡೆಯಿರಿ",

  recoverEyebrow: "ನೀವು ಈಗಾಗಲೇ ಹಣ ಪಾವತಿಸಿದ್ದರೆ",
  recoverTitle: "ಒಂದೊಂದೇ ಹಂತವಾಗಿ ಮುಂದುವರಿಯೋಣ.",
  recoverBody:
    "ಕೆಲವು ಹೌದು-ಇಲ್ಲ ಪ್ರಶ್ನೆಗಳು, ಇದರಿಂದ ಹಂತಗಳು ನಡೆದದ್ದಕ್ಕೆ ಹೊಂದುತ್ತವೆ. ಇಲ್ಲಿಂದ ಯಾರಿಗೂ ಏನೂ ಕಳುಹಿಸಲಾಗುವುದಿಲ್ಲ.",
  recoverPaid: "ನಿಮ್ಮ ಖಾತೆಯಿಂದ ಹಣ ಹೋಯಿತೇ?",
  recoverMethod: "ನೀವು ಹೇಗೆ ಪಾವತಿಸಿದಿರಿ?",
  recoverInstalled: "ಅವರು ಕಳುಹಿಸಿದ ಆ್ಯಪ್ ಇನ್‌ಸ್ಟಾಲ್ ಮಾಡಿದಿರಾ, ಅಥವಾ ನಿಮ್ಮ ಸ್ಕ್ರೀನ್ ಹಂಚಿಕೊಂಡಿರಾ?",
  recoverBroker: "ಇದು ನಿಮ್ಮ ಸ್ವಂತ ನೋಂದಾಯಿತ ಬ್ರೋಕರ್ ಅಥವಾ ಡಿಮ್ಯಾಟ್ ಖಾತೆಗೆ ಸಂಬಂಧಿಸಿದ್ದೇ?",
  recoverUnauthorised: "ನೀವು ಮಾಡದ ಟ್ರೇಡ್ ನಿಮ್ಮ ಖಾತೆಯಲ್ಲಿ ನಡೆಯಿತೇ?",
  recoverCannotWithdraw: "ಯಾವುದಾದರೂ ವೇದಿಕೆ ನಿಮಗೆ ಹಣ ತೆಗೆಯಲು ಬಿಡುತ್ತಿಲ್ಲವೇ?",
  yes: "ಹೌದು",
  no: "ಇಲ್ಲ",
  paymentMethods: {
    upi: "UPI",
    bank_transfer: "ಬ್ಯಾಂಕ್ ವರ್ಗಾವಣೆ",
    card: "ಕಾರ್ಡ್",
    cash_or_other: "ನಗದು ಅಥವಾ ಇತರೆ",
    none: "ಅನ್ವಯಿಸುವುದಿಲ್ಲ",
  },
  recoverSubmit: "ಏನು ಮಾಡಬೇಕೆಂದು ತೋರಿಸಿ",
  recoverFooter: "Ruko ಖಾತೆ ಸಂಖ್ಯೆ, OTP ಅಥವಾ PIN ಕೇಳುವುದಿಲ್ಲ, ಮತ್ತು ನಿಮ್ಮ ಪರವಾಗಿ ಏನನ್ನೂ ಕಳುಹಿಸುವುದಿಲ್ಲ.",

  mirrorEyebrow: "ನನ್ನ ಮಾದರಿಗಳು",
  mirrorTitle: "ನಿಮ್ಮ ಸ್ವಂತ ದಿನಚರಿ ಏನು ತೋರಿಸುತ್ತದೆ.",
  mirrorBody:
    "ನಿಮ್ಮ ದಿನಚರಿಯಿಂದ ಲೆಕ್ಕ ಹಾಕಿದ್ದು. ಈ ನೋಟಕ್ಕಾಗಿ ಕೇವಲ ದಾಖಲೆಗಳನ್ನು ಕಳುಹಿಸಲಾಗುತ್ತದೆ, ಟಿಪ್ಪಣಿಗಳನ್ನಲ್ಲ, ಮತ್ತು ಏನನ್ನೂ ಉಳಿಸಿಕೊಳ್ಳುವುದಿಲ್ಲ.",
  mirrorEmpty: "ಮೊದಲು ನಿಮ್ಮ ದಿನಚರಿಗೆ ಕೆಲವು ನಿರ್ಧಾರಗಳನ್ನು ಸೇರಿಸಿ. ಆಗ ನಿಮ್ಮ ಮಾದರಿಗಳು ಇಲ್ಲಿ ಕಾಣುತ್ತವೆ.",
  mirrorOffline: "ಮಾದರಿಗಳಿಗೆ ಸಂಪರ್ಕ ಬೇಕು. ನಿಮ್ಮ ದಿನಚರಿ ಸಂಪರ್ಕವಿಲ್ಲದೆಯೂ ಕೆಲಸ ಮಾಡುತ್ತದೆ.",
  mirrorOutro: "ಇವು ನಿಮ್ಮ ಸ್ವಂತ ಸಂಖ್ಯೆಗಳು, ಅಂಕ ಅಲ್ಲ. ಕಡಿಮೆ ವಿರಾಮ ಎಂದರೆ ತಾನಾಗಿ ಉತ್ತಮ ಎಂದಲ್ಲ.",
  mirrorMetrics: {
    total_decisions: "ದಿನಚರಿಯಲ್ಲಿನ ನಿರ್ಧಾರಗಳು",
    unsolicited_share_pct: "ಗುಂಪಿನ ಟಿಪ್ ಅಥವಾ ಇನ್‌ಫ್ಲುಯೆನ್ಸರ್‌ನಿಂದ ಆರಂಭವಾದವು",
    plans_set_pct: "ಬರೆದ ಯೋಜನೆ ಇರುವ ನಿರ್ಧಾರಗಳು",
    pauses: "ತೋರಿಸಿದ ವಿರಾಮಗಳು",
    pause_completion_pct: "ನೀವು ಪೂರ್ತಿ ಓದಿದ ವಿರಾಮಗಳು",
    comprehension_pct: "ವಿರಾಮ ಏಕೆ ಬಂತೆಂದು ನೀವು ಹೇಳಬಲ್ಲ ವಿರಾಮಗಳು",
    reconsideration_pct: "ವಿರಾಮದ ನಂತರ ನೀವು ಬದಲಿಸಿದ, ಕಾಯ್ದ ಅಥವಾ ಯೋಜಿಸಿದ ಸಂದರ್ಭಗಳು",
    overrides_with_reason: "ವಿರಾಮದ ನಂತರವೂ ಮುಂದುವರಿದದ್ದು, ಕಾರಣದೊಂದಿಗೆ",
    overrides_without_reason: "ವಿರಾಮದ ನಂತರವೂ ಮುಂದುವರಿದದ್ದು, ಕಾರಣವಿಲ್ಲದೆ",
  },
  mirrorWeekly: "ಪ್ರತಿ ನಿರ್ಧಾರಕ್ಕೆ ವಿರಾಮಗಳು, ವಾರದಿಂದ ವಾರಕ್ಕೆ",
  mirrorWeek: (date: string) => `${date} ರ ವಾರ`,
  mirrorNotEnough: "ಇನ್ನೂ ಸಾಕಾಗುವುದಿಲ್ಲ",

  rulesEyebrow: "ನನ್ನ ನಿಯಮಗಳು",
  rulesTitle: "ನಿಮ್ಮ ಬದ್ಧತೆಗಳು, ನಿಮ್ಮ ಷರತ್ತುಗಳಲ್ಲಿ.",
  rulesBody:
    "ಐಚ್ಛಿಕ. ಈ ಫೋನ್‌ನಲ್ಲಿ ಮಾತ್ರ ಉಳಿಸಲಾಗುತ್ತದೆ ಮತ್ತು ಪ್ರತಿ ಪರಿಶೀಲನೆಯೊಂದಿಗೆ ಕಳುಹಿಸಲಾಗುತ್ತದೆ, ಇದರಿಂದ Ruko ಹೋಲಿಸಬಹುದು.",
  expenses: "ಮಾಸಿಕ ಖರ್ಚು",
  savings: "ಬೇಗ ಸಿಗಬಲ್ಲ ಉಳಿತಾಯ",
  maxShare: "ಒಂದು ನಿರ್ಧಾರದಲ್ಲಿ ನನ್ನ ಉಳಿತಾಯದ ಗರಿಷ್ಠ ಇಷ್ಟು %",
  maxAmount: "ಒಂದು ನಿರ್ಧಾರದಲ್ಲಿ ಗರಿಷ್ಠ ಇಷ್ಟು ರೂಪಾಯಿ",
  emergencyBuffer: "ಖರ್ಚಿನ ಎಷ್ಟು ತಿಂಗಳುಗಳನ್ನು ನಾನು ಮುಟ್ಟದೆ ಇಡಲು ಬಯಸುತ್ತೇನೆ",
  protectedGoal: "ಗುರಿಗಾಗಿ ಬದಿಗಿಟ್ಟ ಹಣ, ಇದನ್ನು ನಾನು ಮುಟ್ಟುವುದಿಲ್ಲ (₹)",
  noBorrowed: "ನಾನು ಸಾಲದ ಹಣ ಹೂಡುವುದಿಲ್ಲ",
  coolingRule: "ಕ್ರಮ ಕೈಗೊಳ್ಳುವ ಮೊದಲು ನಾನು ಕಾಯಲು ಬಯಸುವ ನಿಮಿಷಗಳು",
  notSet: "ಹೊಂದಿಸಿಲ್ಲ",
  save: "ಉಳಿಸಿ",
  saved: "ಈ ಫೋನ್‌ನಲ್ಲಿ ಉಳಿಸಲಾಗಿದೆ",
  saveFailed: "ಈ ಫೋನ್ ಉಳಿಸಲು ಅನುಮತಿಸಲಿಲ್ಲ.",

  settingsEyebrow: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
  settingsTitle: "Ruko ವನ್ನು ನಿಮಗೆ ತಕ್ಕಂತೆ ಮಾಡಿ.",
  languageLabel: "ಭಾಷೆ",
  languageDraft: "ಹಿಂದಿ ಮತ್ತು ಕನ್ನಡ ಪಠ್ಯ ಇನ್ನೂ ಕರಡು, ಸ್ಥಳೀಯ ಭಾಷಿಕರ ಪರಿಶೀಲನೆ ಬಾಕಿ ಇದೆ.",
  largeText: "ದೊಡ್ಡ ಅಕ್ಷರಗಳು",
  styleLabel: "Ruko ಎಷ್ಟು ಮಾತನಾಡಬೇಕು?",
  styleQuiet: "ಶಾಂತ: ಅಗತ್ಯವಾದದ್ದು ಮಾತ್ರ",
  styleBalanced: "ಸಮತೋಲನ: ಏನಾದರೂ ಎದ್ದುಕಂಡರೆ ಒಂದು ಚಿಕ್ಕ ಟಿಪ್ಪಣಿ",
  styleNote: "ಮುಖ್ಯವಾದುದನ್ನು Ruko ಈಗಲೂ ಹೇಳುತ್ತದೆ. ಇದು ಐಚ್ಛಿಕ ಹೆಚ್ಚುವರಿಗಳನ್ನು ಮಾತ್ರ ಕಡಿಮೆ ಮಾಡುತ್ತದೆ.",
  exportTitle: "ನನ್ನ ಅನಾಮಧೇಯ ಸಾರಾಂಶ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ",
  exportBody: "ಕೇವಲ ಎಣಿಕೆಗಳು: ಸಂದೇಶ, ಮೊತ್ತ ಅಥವಾ ಟಿಪ್ಪಣಿ ಇಲ್ಲ. ಪೈಲಟ್‌ಗಾಗಿ, ನೀವು ಹಂಚಿಕೊಳ್ಳಲು ಬಯಸಿದರೆ.",
  exportButton: "ಸಾರಾಂಶ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ",
  exportDone: "ಸಾರಾಂಶ ಡೌನ್‌ಲೋಡ್ ಆಯಿತು.",
  demoMenu: "ಡೆಮೊ ಸಾಧನಗಳು",
  demoBroker: "ಕಾಲ್ಪನಿಕ ಬ್ರೋಕರ್ ಡೆಮೊ",
  versionLine: "Ruko ಮಾದರಿ",

  onboardEyebrow: "ಸ್ವಾಗತ",
  onboardLanguageTitle: "ನಿಮ್ಮ ಭಾಷೆ ಆರಿಸಿ",
  onboardLanguageBody: "ನೀವು ಇದನ್ನು ಯಾವಾಗ ಬೇಕಾದರೂ ಸೆಟ್ಟಿಂಗ್‌ಗಳಲ್ಲಿ ಬದಲಿಸಬಹುದು.",
  onboardRulesTitle: "ಬೇಕಿದ್ದರೆ ನಿಮ್ಮ ಸ್ವಂತ ನಿಯಮಗಳನ್ನು ಹೊಂದಿಸಿ.",
  onboardRulesBody:
    "ಶಾಂತವಾಗಿರುವಾಗ ಬರೆದ ನಿಯಮಗಳನ್ನೇ Ruko ನಂತರ ನಿಮಗೆ ತೋರಿಸುತ್ತದೆ. ಎಲ್ಲವೂ ಐಚ್ಛಿಕ, ಮತ್ತು ಈ ಫೋನ್‌ನಲ್ಲೇ ಇರುತ್ತವೆ.",
  onboardStyleTitle: "Ruko ಎಷ್ಟು ಮಾತನಾಡಬೇಕು?",
  onboardNext: "ಮುಂದೆ",
  onboardStart: "Ruko ಬಳಸಲು ಪ್ರಾರಂಭಿಸಿ",
  onboardSkip: "ಬಿಟ್ಟುಬಿಡಿ, ಸುರಕ್ಷಿತ ಡೀಫಾಲ್ಟ್ ಬಳಸಿ",
  onboardSafeDefaults:
    "ಸುರಕ್ಷಿತ ಡೀಫಾಲ್ಟ್: ನೀವು ಯಾವ ನಿಯಮವನ್ನೂ ಹೊಂದಿಸಿಲ್ಲ, ಮತ್ತು Ruko ತಾನೇ ಮಾಡಿದ ಯಾವುದೇ ಸಂಖ್ಯೆಯೊಂದಿಗೆ ಹೋಲಿಸುವುದಿಲ್ಲ.",


  // --- Adaptive questions, refine, quotes, plans, calculator, home (A to F). DRAFT. ---
  clarifyContinue: "ಮುಂದುವರಿಸಿ",
  clarifyChooseOne: "ಒಂದನ್ನು ಆರಿಸಿ.",
  clarifyAnswerAfterSkip: "ಆದರೂ ಹೇಳುತ್ತೇನೆ",
  lastTime: "ಕಳೆದ ಬಾರಿ",
  aboutYouTitle: "ನಿಮ್ಮ ಬಗ್ಗೆ ಸ್ವಲ್ಪ (ಐಚ್ಛಿಕ)",
  aboutYouNote: "ಒಮ್ಮೆ ಮಾತ್ರ ಕೇಳಲಾಗುತ್ತದೆ ಮತ್ತು ಈ ಫೋನ್‌ನಲ್ಲೇ ಇರುತ್ತದೆ. ಇದು Ruko ಹೋಲಿಸಲು ಮಾತ್ರ ಸಹಾಯ ಮಾಡುತ್ತದೆ.",
  experienceQuestion: "ಈ ರೀತಿಯ ನಿರ್ಧಾರ ನಿಮಗೆ ಎಷ್ಟು ಪರಿಚಿತ?",
  experienceOptions: {
    none: "ನನಗೆ ಹೊಸದು",
    some: "ಕೆಲವು ಬಾರಿ ಮಾಡಿದ್ದೇನೆ",
    regular: "ನಾನು ಇದನ್ನು ನಿಯಮಿತವಾಗಿ ಮಾಡುತ್ತೇನೆ",
  },
  recentLossQuestion: "ಇತ್ತೀಚೆಗೆ ನಿಮಗೆ ನಷ್ಟವಾಗಿದೆಯೇ?",
  recentLossOptions: { yes: "ಹೌದು, ಇತ್ತೀಚೆಗೆ", no: "ಇಲ್ಲ" },
  tradesQuestion: "ಈ ವಾರ ನೀವು ಎಷ್ಟು ಟ್ರೇಡ್ ಮಾಡಿದ್ದೀರಿ?",
  tradesOptions: { "0": "ಯಾವುದೂ ಇಲ್ಲ", "1_5": "1 ರಿಂದ 5", "6_20": "6 ರಿಂದ 20", gt_20: "20 ಕ್ಕಿಂತ ಹೆಚ್ಚು" },

  refineTitle: "ಇದನ್ನು ನಿಮ್ಮ ಹಣದ ಲೆಕ್ಕದಲ್ಲಿ ನೋಡಿ",
  refineBody: "ನಿಮ್ಮ ಸ್ವಂತ ಸಂಖ್ಯೆಗಳನ್ನು ಸೇರಿಸಿ, ಆಗ Ruko ಇದು ನಿಮಗೆ ಏನು ಅರ್ಥ ಎಂದು ತೋರಿಸುತ್ತದೆ.",
  refineButton: "ನನಗೆ ಇದರ ಅರ್ಥ ತೋರಿಸಿ",

  yourMessageTitle: "ನಿಮ್ಮ ಸಂದೇಶ, ಮತ್ತು Ruko ಗಮನಿಸಿದ್ದು",
  fromYourMessage: "ನಿಮ್ಮ ಸಂದೇಶದಿಂದ",
  showMessage: "ನನ್ನ ಸಂದೇಶ ತೋರಿಸಿ",
  hideMessage: "ನನ್ನ ಸಂದೇಶ ಮರೆಮಾಡಿ",

  reflectByReason: {
    UNSOLICITED_SOURCE: "ಇದನ್ನು ನನಗೆ ಪರಿಚಯವಿಲ್ಲದವರು ಕಳುಹಿಸಿದ್ದಾರೆ",
    URGENCY_PRESSURE: "ಕೊನೆಯ ದಿನಾಂಕ ನನ್ನ ಮೇಲೆ ಒತ್ತಡ ಹಾಕುತ್ತಿದೆ",
    GUARANTEED_RETURN_CLAIM: "ಭರವಸೆ ನೀಡಿದ ಲಾಭ ಆಕರ್ಷಕವಾಗಿ ಕಾಣುತ್ತಿದೆ",
    PROFIT_SCREENSHOT_SOCIAL_PROOF: "ಬೇರೆಯವರು ಹಣ ಗಳಿಸುತ್ತಿರುವಂತೆ ಕಾಣುತ್ತದೆ",
    AUTHORITY_CLAIM: "ಅವರು ತುಂಬಾ ತಿಳಿದವರಂತೆ ಮಾತನಾಡುತ್ತಾರೆ",
    POST_LOSS_REENTRY_DECLARED: "ನಾನು ಹಿಂದಿನ ನಷ್ಟವನ್ನು ಮರಳಿ ಪಡೆಯಲು ಬಯಸುತ್ತೇನೆ",
    LATE_NIGHT_DECISION: "ತಡವಾಗಿದೆ, ಇದನ್ನು ಈಗಲೇ ಮುಗಿಸಬೇಕು",
    HIGH_FREQUENCY_DECLARED: "ನನಗೆ ಸಕ್ರಿಯ ಟ್ರೇಡಿಂಗ್ ಇಷ್ಟ",
    FIRST_TIME_PRODUCT: "ಹೊಸದನ್ನು ಪ್ರಯತ್ನಿಸುವ ಕುತೂಹಲ ನನಗಿದೆ",
  } as Record<string, string>,
  reflectFomo: "ಅವಕಾಶ ತಪ್ಪುವ ಭಯವಿದೆ",
  reflectTrusted: "ನಾನು ನಂಬುವವರು ಇದನ್ನು ಶಿಫಾರಸು ಮಾಡಿದರು",
  reflectUnderstand: "ನಾನು ಇದನ್ನು ಅರ್ಥಮಾಡಿಕೊಂಡಿದ್ದೇನೆ ಮತ್ತು ಯೋಚಿಸಿದ್ದೇನೆ",
  reflectOther: "ಬೇರೆ ಏನೋ",
  decideNow: "ನಿರ್ಧರಿಸಿ",
  reflectOptional: "ಮೊದಲು ಕಾರಣ ಸೇರಿಸಿ (ಐಚ್ಛಿಕ)",
  paceNote: "ನೀವು ಸಾಮಾನ್ಯವಾಗಿ ಯೋಚಿಸುವ ಹಂತವನ್ನು ಬಿಡುತ್ತೀರಿ, ಆದ್ದರಿಂದ Ruko ಅದನ್ನು ಬಿಡುತ್ತಿದೆ. ಬೇಕಿದ್ದರೆ ಕಾರಣ ಸೇರಿಸಬಹುದು.",
  changeAmountTitle: "ಬದಲಿಗೆ ಯಾವ ಮೊತ್ತವನ್ನು ಪರಿಶೀಲಿಸಲು ಬಯಸುತ್ತೀರಿ?",
  changeAmountButton: "ಈ ಮೊತ್ತ ಪರಿಶೀಲಿಸಿ",
  amountPlaceholder: "ಮೊತ್ತ ₹ ನಲ್ಲಿ",
  planAddedNote: "ಯೋಜನೆ ಸೇರಿಸಲಾಗಿದೆ. Ruko ಅದರೊಂದಿಗೆ ಮತ್ತೆ ಪರಿಶೀಲಿಸಿತು.",

  planEyebrow: "ನಿಮ್ಮ ಯೋಜನೆ",
  planTitle: "ನಿಮ್ಮ ಯೋಜನೆಯನ್ನು ನಿಮ್ಮ ಮಾತುಗಳಲ್ಲಿ ಬರೆಯಿರಿ.",
  planBody:
    "ಮಾತುಗಳು ಈ ಫೋನ್‌ನಲ್ಲೇ ಇರುತ್ತವೆ. ನೀವು ಯಾವ ಭಾಗಗಳನ್ನು ಬರೆದಿರಿ ಎಂದು ಮಾತ್ರ Ruko ತಿಳಿಯುತ್ತದೆ, ಇದರಿಂದ ಯೋಜನೆ ಪೂರ್ಣವೇ ಎಂದು ನೋಡಬಹುದು.",
  planReason: "ನಾನು ಇದನ್ನು ಏಕೆ ಮಾಡುತ್ತಿದ್ದೇನೆ?",
  planHorizon: "ನಾನು ಎಷ್ಟು ಕಾಲ ಇರಲು ಬಯಸುತ್ತೇನೆ?",
  planHorizonOptions: {
    days: "ಕೆಲವು ದಿನ",
    weeks: "ಕೆಲವು ವಾರ",
    months: "ಕೆಲವು ತಿಂಗಳು",
    years: "ವರ್ಷಗಳು",
    unsure: "ಇನ್ನೂ ಖಚಿತವಿಲ್ಲ",
  },
  planReconsider: "ಯಾವುದು ನನ್ನನ್ನು ಮತ್ತೆ ಯೋಚಿಸುವಂತೆ ಅಥವಾ ಹೊರಬರುವಂತೆ ಮಾಡುತ್ತದೆ?",
  planRangeTitle: "ಈ ಯೋಜನೆಯ ಮೊತ್ತದ ವ್ಯಾಪ್ತಿ (ಐಚ್ಛಿಕ)",
  planFrom: "ಇಂದ ₹",
  planTo: "ವರೆಗೆ ₹",
  planSave: "ಇದನ್ನು ಈ ರೀತಿಯ ನಿರ್ಧಾರದ ಯೋಜನೆಯಾಗಿ ಇಟ್ಟುಕೊಳ್ಳಿ",
  planSubmit: "ಈ ಯೋಜನೆ ಬಳಸಿ",
  planEmpty: "ಯೋಜನೆಯ ಕನಿಷ್ಠ ಒಂದು ಭಾಗ ಬರೆಯಿರಿ: ಏಕೆ, ಎಷ್ಟು ಕಾಲ, ಅಥವಾ ಯಾವುದು ನಿಮ್ಮನ್ನು ಮತ್ತೆ ಯೋಚಿಸುವಂತೆ ಮಾಡುತ್ತದೆ.",
  planRangeInvalid: "ಎರಡೂ ಮೊತ್ತಗಳನ್ನು ಪೂರ್ಣ ರೂಪಾಯಿಗಳಲ್ಲಿ ಬರೆಯಿರಿ, ಮೊದಲನೆಯದು ಎರಡನೆಯದಕ್ಕಿಂತ ಹೆಚ್ಚಿರಬಾರದು.",
  plansTitle: "ನನ್ನ ಯೋಜನೆಗಳು",
  plansEmpty: "ಇನ್ನೂ ಯೋಜನೆ ಇಲ್ಲ. ನಿರ್ಧಾರ ಬಂದಾಗ ನೀವು ಒಂದನ್ನು ಬರೆಯಬಹುದು.",
  planRemove: "ತೆಗೆದುಹಾಕಿ",
  planRange: (min: string, max: string) => `${min} ರಿಂದ ${max}`,

  calcToolTitle: "ನಿಮ್ಮ ಸ್ವಂತ ಸಂಖ್ಯೆಗಳನ್ನು ಪ್ರಯತ್ನಿಸಿ",
  calcToolBody:
    "ಯಾವುದೇ ಸಂಖ್ಯೆ ಬದಲಿಸಿ, ಫಲಿತಾಂಶ ಬದಲಾಗುತ್ತದೆ. ಇದು ನಿಮ್ಮ ಊಹೆಗಳ ಮೇಲಿನ ಲೆಕ್ಕ, ಮುನ್ಸೂಚನೆ ಅಲ್ಲ.",
  calcTools: {
    sip: "ಒಂದು SIP",
    goal: "ಒಂದು ಗುರಿ",
    inflation: "ಹಣದುಬ್ಬರ",
    consequence: "ಮೌಲ್ಯದಲ್ಲಿ ಇಳಿಕೆ",
    costs: "ಟ್ರೇಡಿಂಗ್ ವೆಚ್ಚ",
  },
  calcFields: {
    monthly_inr: "ಮಾಸಿಕ ಮೊತ್ತ (₹)",
    months: "ತಿಂಗಳುಗಳ ಸಂಖ್ಯೆ",
    goal_inr: "ಗುರಿಯ ಮೊತ್ತ (₹)",
    already_saved_inr: "ಈಗಾಗಲೇ ಉಳಿಸಿದ್ದು (₹, ಐಚ್ಛಿಕ)",
    amount_inr: "ಮೊತ್ತ (₹)",
    years: "ವರ್ಷಗಳ ಸಂಖ್ಯೆ",
    leverage: "ಲೆವರೇಜ್, ಎಷ್ಟು ಪಟ್ಟು (1 ಎಂದರೆ ಇಲ್ಲ)",
    trade_value_inr: "ಒಂದು ಟ್ರೇಡ್‌ನ ಮೌಲ್ಯ (₹)",
    trades_per_month: "ಒಂದು ತಿಂಗಳಲ್ಲಿ ಟ್ರೇಡ್‌ಗಳು",
  },
  calcRates: "ಪ್ರಯತ್ನಿಸಲು ವಾರ್ಷಿಕ ದರಗಳು (%)",
  calcDrops: "ಪ್ರಯತ್ನಿಸಲು ಇಳಿಕೆಗಳು (%)",
  calcAddRate: "ಸೇರಿಸಿ",
  calcRatePlaceholder: "ಉದಾ. 8",
  calcRateNote: "ನಿಮ್ಮ ಸ್ವಂತ ದರಗಳು Ruko ದ ಹೆಸರಿಸಿದ ಉದಾಹರಣೆ ದರಗಳ ಪಕ್ಕದಲ್ಲಿ ಕಾಣುತ್ತವೆ.",
  calcRemove: (value: string) => `${value} ತೆಗೆದುಹಾಕಿ`,
  calcUpdating: "ನವೀಕರಿಸಲಾಗುತ್ತಿದೆ…",
  calcFillIn: "ಫಲಿತಾಂಶ ನೋಡಲು ಮೇಲಿನ ಸಂಖ್ಯೆಗಳನ್ನು ತುಂಬಿ.",
  calcAdjust: "ಈ ಸಂಖ್ಯೆಗಳನ್ನು ಬದಲಿಸಿ",

  waitDueTitle: "ನಿಮ್ಮ ಕಾಯುವಿಕೆ ಮುಗಿಯಿತು",
  waitPendingTitle: "ನೀವು ಕಾಯಲು ನಿರ್ಧರಿಸಿದ್ದೀರಿ",
  waitDueBody: "ಇನ್ನೂ ಇದರ ಬಗ್ಗೆ ಯೋಚಿಸುತ್ತಿದ್ದೀರಾ? ಎರಡೂ ರೀತಿಯಲ್ಲಿ ನಿರ್ಧಾರ ನಿಮ್ಮದು.",
  waitPendingBody: "ಕಾಯುವಿಕೆ ಮುಗಿದ ಮೇಲೆ Ruko ಮತ್ತೆ ಕೇಳುತ್ತದೆ.",
  waitLookAgain: "ಇದನ್ನು ಮತ್ತೆ ನೋಡಿ",
  waitLetGo: "ನಾನು ಇದನ್ನು ಬಿಟ್ಟುಬಿಟ್ಟೆ",
  planFollowTitle: "ನೀವು ನಿಮ್ಮ ಯೋಜನೆಯನ್ನು ಅನುಸರಿಸಿದಿರಾ?",
  planFollowBody: (date: string) => `ನೀವು ${date} ರಂದು ಯೋಜನೆ ಬರೆದಿದ್ದಿರಿ.`,
  planYes: "ಹೌದು",
  planNo: "ಈ ಬಾರಿ ಇಲ್ಲ",
  planNotYet: "ಇನ್ನೂ ಇಲ್ಲ",
  homeBack: "ಮತ್ತೆ ಸ್ವಾಗತ.",
  notNow: "ಈಗ ಬೇಡ",
  moneyCheckText: "ಹೂಡಿಕೆ ಮಾಡಲು ಯೋಚಿಸುತ್ತಿದ್ದೇನೆ",
  homeRulesNudgeTitle: "ನಿಮ್ಮ ಒಂದು ನಿಯಮವನ್ನು ಹೊಂದಿಸಿ",
  homeRulesNudgeBody: "ನೀವು ಶಾಂತವಾಗಿ ನಿರ್ಧರಿಸಿದಾಗ, Ruko ಅದನ್ನು ನಂತರ ನಿಮಗೆ ನೆನಪಿಸಬಹುದು.",
  homeRulesNudgeButton: "ನಿಯಮ ಹೊಂದಿಸಿ",
  homePatternsNudgeTitle: "ನಿಮ್ಮ ದಿನಚರಿ ಏನು ತೋರಿಸುತ್ತದೆ ನೋಡಿ",
  homePatternsNudgeBody: "ನಿಮ್ಮ ಕೆಲವು ನಿರ್ಧಾರಗಳು ದಾಖಲಾಗಿವೆ.",
  bridgeMoney: "ಒಂದು ಮೊತ್ತ ನನ್ನ ಹಣಕ್ಕೆ ಏನು ಅರ್ಥ ಎಂದು ತೋರಿಸಿ",
  bridgeMoneyNote:
    "ಕೊಳ್ಳಬೇಕೇ ಎಂದು Ruko ಹೇಳಲಾಗದು, ಆದರೆ ಒಂದು ಮೊತ್ತ ನಿಮ್ಮ ಉಳಿತಾಯ ಮತ್ತು ನಿಯಮಗಳಿಗೆ ಏನು ಅರ್ಥ ಎಂದು ತೋರಿಸಬಹುದು.",
  bridgeFall: "ಇಳಿಕೆ ರೂಪಾಯಿಗಳಲ್ಲಿ ಏನಾಗುತ್ತದೆ ನೋಡಿ",
  bridgeFallNote: "ಮುಂದೆ ಏನಾಗುತ್ತದೆ ಎಂದು ಯಾರೂ ಹೇಳಲಾಗದು, ಆದರೆ ಇಳಿಕೆಯ ಲೆಕ್ಕ ಕೇವಲ ಗಣಿತ.",
  glossaryMore: "Ruko ವಿವರಿಸಬಲ್ಲ ಇನ್ನಷ್ಟು ಪದಗಳು",
  profileExperience: "ಪ್ರತಿಯೊಂದರ ಬಗ್ಗೆ ನನಗೆ ಎಷ್ಟು ಪರಿಚಯ (ಐಚ್ಛಿಕ)",
  ageBandLabel: "ನನ್ನ ವಯಸ್ಸು (ಐಚ್ಛಿಕ)",
  ageBands: {
    lt_30: "30 ಕ್ಕಿಂತ ಕಡಿಮೆ",
    "30_40": "30 ರಿಂದ 40",
    "40_50": "40 ರಿಂದ 50",
    "50_60": "50 ರಿಂದ 60",
    gt_60: "60 ಕ್ಕಿಂತ ಹೆಚ್ಚು",
  },
  productNames: {
    cash_equity: "ಕಂಪನಿ ಷೇರುಗಳು",
    derivative: "ಫ್ಯೂಚರ್ಸ್ ಅಥವಾ ಆಪ್ಷನ್ಸ್ (F&O)",
    ipo: "ಒಂದು IPO",
    mutual_fund: "ಒಂದು ಮ್ಯೂಚುಯಲ್ ಫಂಡ್",
    crypto: "ಕ್ರಿಪ್ಟೋ",
  },

  offlineNote:
    "ನೀವು ಆಫ್‌ಲೈನ್ ಇದ್ದೀರಿ. ನಿಮ್ಮ ನಿಯಮಗಳು, ದಿನಚರಿ ಮತ್ತು ಪರಿಶೀಲನಾ ಪಟ್ಟಿ ಈಗಲೂ ಕೆಲಸ ಮಾಡುತ್ತವೆ. ಸಂದೇಶ ಪರಿಶೀಲಿಸಲು ಸಂಪರ್ಕ ಬೇಕು.",

  errorEyebrow: "ಏನೋ ತಪ್ಪಾಯಿತು",
  errors: {
    backend_unavailable: "ಈಗ Ruko ವನ್ನು ತಲುಪಲು ಸಾಧ್ಯವಿಲ್ಲ. ನಿಮ್ಮ ಸಂಪರ್ಕ ನೋಡಿ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    timeout: "ಇದಕ್ಕೆ ಸಾಮಾನ್ಯಕ್ಕಿಂತ ಹೆಚ್ಚು ಸಮಯ ಹಿಡಿಯುತ್ತಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    invalid_response: "Ruko ಗೆ ಓದಲಾಗದ ಉತ್ತರ ಬಂತು. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    unsupported_input: "Ruko ಈ ರೀತಿಯ ಫೈಲ್ ಓದಲು ಸಾಧ್ಯವಿಲ್ಲ. ಬದಲಿಗೆ ಪಠ್ಯ ಅಂಟಿಸಿ ನೋಡಿ.",
    reading_unavailable:
      "ಈಗ Ruko ಸ್ಕ್ರೀನ್‌ಶಾಟ್ ಅಥವಾ ಧ್ವನಿ ಓದಲು ಸಾಧ್ಯವಿಲ್ಲ. ಬದಲಿಗೆ ಪಠ್ಯ ಅಂಟಿಸಿ ನೋಡಿ.",
    too_many_requests: "ಕಡಿಮೆ ಸಮಯದಲ್ಲಿ ತುಂಬಾ ಪರಿಶೀಲನೆಗಳಾದವು. ಒಂದು ನಿಮಿಷ ಕಾಯ್ದು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    invalid_request: "Ruko ಆ ಇನ್‌ಪುಟ್ ಬಳಸಲಾಗಲಿಲ್ಲ. ಸಂದೇಶವನ್ನು ಮತ್ತೆ ಅಂಟಿಸಿ ನೋಡಿ.",
    server_error: "Ruko ದ ಕಡೆ ಏನೋ ತಪ್ಪಾಯಿತು. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
  },
  tryAgain: "ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ",
  startOver: "ಮತ್ತೆ ಪ್ರಾರಂಭಿಸಿ",
};
